### ISSUE TITLE
Got error while processing diagnostics: readCreateProcess

### ISSUE THREAD

**Issue by Raffiki** [haskell/haskell-ide-engine#1468] opened 2019-11-24 14:13 UTC
I try to use the `all-hies` cached hie in a GHC-864 project with cabal 3.0.0. 
```
Got error while processing diagnostics: readCreateProcess: /nix/store/2n76ggk9kx279ng7qpnryv7fg5rgiqy4-cabal-helper-0.9.0.0/bin/cabal-helper-wrapper "--with-ghc=ghc" "--with-ghc-pkg=ghc-pkg" "--with-cabal=cabal" "v1-style" "/home/raf/Projects/raf/fp-course" "/home/raf/Projects/raf/fp-course/dist-newstyle/build/x86_64-linux/ghc-8.6.4/course-0.1.4" "package-db-stack" "flags" "compiler-version" "ghc-merged-pkg-options" "config-flags" "non-default-config-flags" "ghc-src-options" "ghc-pkg-options" "ghc-lang-options" "ghc-options" "source-dirs" "entrypoints" "needs-build-output" (exit 1): failed
```

when I run the mentioned command with `--verbose` I get:

```
/nix/store/2n76ggk9kx279ng7qpnryv7fg5rgiqy4-cabal-helper-0.9.0.0/bin/cabal-helper-wrapper --verbose "--with-ghc=ghc" "--with-ghc-pkg=ghc-pkg" "--with-cabal=cabal" "v1-style" "/home/raf/Projects/raf/fp-course" "/home/raf/Projects/raf/fp-course/dist-newstyle/build/x86_64-linux/ghc-8.6.4/course-0.1.4" "package-db-stack" "flags" "compiler-version" "ghc-merged-pkg-options" "config-flags" "non-default-config-flags" "ghc-src-options" "ghc-pkg-options" "ghc-lang-options" "ghc-options" "source-dirs" "entrypoints" "needs-build-output"
Searching for ghc in path.
Found ghc at /usr/local/bin/ghc
/usr/local/bin/ghc --numeric-version
/usr/local/bin/ghc is version 8.6.4
looking for tool ghc-pkg near compiler in /usr/local/bin
candidate locations:
["/usr/local/bin/ghc-pkg","/usr/local/bin/ghc-pkg-ghc-8.6.4","/usr/local/bin/ghc-pkg-8.6.4","/usr/local/bin/ghc-pkg"]
found ghc-pkg in /usr/local/bin/ghc-pkg
/usr/local/bin/ghc-pkg --version
/usr/local/bin/ghc-pkg is version 8.6.4
/usr/local/bin/ghc --supported-languages
/usr/local/bin/ghc --info
/usr/local/bin/ghc-pkg --numeric-version
=> 8.6.4

/usr/local/bin/ghc-pkg list --simple-output Cabal
=> Cabal-2.4.0.1 Cabal-3.0.0.0

using helper compiled with Cabal from user/global package-db
helper exe does not exist, compiling /home/raf/.cache/cabal-helper/cabal-helper0.9.0.0-Cabal3.0.0.0
compSrcDir: /home/raf/.cache/cabal-helper/cabal-helper0.9.0.0-Cabal3.0.0.0.build
compOutDir: /home/raf/.cache/cabal-helper/cabal-helper0.9.0.0-Cabal3.0.0.0.build
compExePath: /home/raf/.cache/cabal-helper/cabal-helper0.9.0.0-Cabal3.0.0.0
/usr/local/bin/ghc -outputdir /home/raf/.cache/cabal-helper/cabal-helper0.9.0.0-Cabal3.0.0.0.build -o /home/raf/.cache/cabal-helper/cabal-helper0.9.0.0-Cabal3.0.0.0 -optP-DCABAL_HELPER=1 '-optP-DCH_MIN_VERSION_Cabal(major1,major2,minor)=(  (major1)  < 3 || (major1) == 3 && (major2)  < 0 || (major1) == 3 && (major2) == 0 && (minor) <= 0)' -i -i/home/raf/.cache/cabal-helper/cabal-helper0.9.0.0-Cabal3.0.0.0.build -hide-all-packages -package base -package containers -package directory -package filepath -package process -package bytestring -package ghc-prim -package Cabal-3.0.0.0 -w --make /home/raf/.cache/cabal-helper/cabal-helper0.9.0.0-Cabal3.0.0.0.build/CabalHelper/Runtime/Main.hs
[1 of 4] Compiling CabalHelper.Shared.Common ( /home/raf/.cache/cabal-helper/cabal-helper0.9.0.0-Cabal3.0.0.0.build/CabalHelper/Shared/Common.hs, /home/raf/.cache/cabal-helper/cabal-helper0.9.0.0-Cabal3.0.0.0.build/CabalHelper/Shared/Common.o )
[2 of 4] Compiling CabalHelper.Shared.InterfaceTypes ( /home/raf/.cache/cabal-helper/cabal-helper0.9.0.0-Cabal3.0.0.0.build/CabalHelper/Shared/InterfaceTypes.hs, /home/raf/.cache/cabal-helper/cabal-helper0.9.0.0-Cabal3.0.0.0.build/CabalHelper/Shared/InterfaceTypes.o )
[3 of 4] Compiling CabalHelper.Shared.Sandbox ( /home/raf/.cache/cabal-helper/cabal-helper0.9.0.0-Cabal3.0.0.0.build/CabalHelper/Shared/Sandbox.hs, /home/raf/.cache/cabal-helper/cabal-helper0.9.0.0-Cabal3.0.0.0.build/CabalHelper/Shared/Sandbox.o )
[4 of 4] Compiling Main             ( /home/raf/.cache/cabal-helper/cabal-helper0.9.0.0-Cabal3.0.0.0.build/CabalHelper/Runtime/Main.hs, /home/raf/.cache/cabal-helper/cabal-helper0.9.0.0-Cabal3.0.0.0.build/Main.o )

/home/raf/.cache/cabal-helper/cabal-helper0.9.0.0-Cabal3.0.0.0.build/CabalHelper/Runtime/Main.hs:27:5: error:
    Module ‘Distribution.Package’ does not export ‘InstalledPackageId’
   |
27 |   , InstalledPackageId
   |     ^^^^^^^^^^^^^^^^^^

/home/raf/.cache/cabal-helper/cabal-helper0.9.0.0-Cabal3.0.0.0.build/CabalHelper/Runtime/Main.hs:66:5: error:
    Module
    ‘Distribution.Simple.LocalBuildInfo’
    does not export
    ‘externalPackageDeps’
   |
66 |   , externalPackageDeps
   |     ^^^^^^^^^^^^^^^^^^^

/home/raf/.cache/cabal-helper/cabal-helper0.9.0.0-Cabal3.0.0.0.build/CabalHelper/Runtime/Main.hs:67:5: error:
    Module
    ‘Distribution.Simple.LocalBuildInfo’
    does not export
    ‘withComponentsLBI’
   |
67 |   , withComponentsLBI
   |     ^^^^^^^^^^^^^^^^^

/home/raf/.cache/cabal-helper/cabal-helper0.9.0.0-Cabal3.0.0.0.build/CabalHelper/Runtime/Main.hs:87:5: error:
    Module
    ‘Distribution.Simple.BuildPaths’
    does not export
    ‘autogenModuleName’
   |
87 |   ( autogenModuleName
   |     ^^^^^^^^^^^^^^^^^
```

unregistered cabal 2.4 but same story

```
/usr/local/bin/ghc-pkg list --simple-output Cabal
=> Cabal-3.0.0.0
```

**Comment by fendor** [comment] 2019-11-24 14:49
Current HIE master does not support Cabal-3.0.0.0. Duplicate of #1376.

**Closed** 2019-11-24 15:58 UTC
