### ISSUE TITLE
Atom + hlint apply fails

### ISSUE THREAD

**Issue by JRikken** [haskell/haskell-ide-engine#1448] opened 2019-11-11 10:49 UTC
Hi, I have ran into an issue with HIE + Atom

## Issue
When applying hlint recommendations, the hint is not applied as expected. I have found two interesting cases: 

- With preceding comments: when the hlint suggestion is preceded by a _single line_ comment `-- some very useful text`, a newline is inserted below the comment
- When no preceding comments are found, nothing happens, the apply action just shows no effect (a multi-line comment preceding the hint has this effect as well)

## Versions
- stack: 2.1.3 with LTS 14.12 & GHC 8.6.5 
- HIE version: hie-8.6.5; version 0.13.0.0. 
- OS: Windows 10 x86_64

**Comment by bubba** [comment] 2019-11-11 14:09
Hi, can you run hie with the `-d` flag and send on the log file of messages? I'm not familiar with how atom records this. For VSCode it's in $TMPDIR/hie.log

**Comment by JRikken** [comment] 2019-11-12 09:46
Hello, I have been playing a bit more with this, and found some additional information. 

I have made a new stack project to test with (`stack new hiebugs`, now I think of it, this did bump my LTS version to 14.14), where `Lib.hs` looks like

```haskell
module Lib
    ( someFunc
    ) where

{- My Multiline -}
someFunc :: IO ()
someFunc = putStrLn myFunc

myFunc :: (String)
myFunc = ("Hello")

-- My single line

```

Interestingly, with this example, when applying the hint to the string literal, the action _does_ have the intended effect (remove the redundant parentheses). However, it still inserts an additional newline after `-- My single line`, even though this line is after the applied hint!

Only when applying the hint to the type signature it does not lead to any effect (other than the inserted newline after the single line comment)!

The log files: 
- [hie_type.log](https://github.com/haskell/haskell-ide-engine/files/3835399/hie_type.log) (when applying to the type signature)
- [hie_literal.log](https://github.com/haskell/haskell-ide-engine/files/3835403/hie_literal.log) (when applying to the string literal)

**Comment by jneira** [comment] 2019-11-14 00:52
Thanks for the report @JRikken. Another windows user here 😄 
I suspect that apply refactors doesnt work in vscode neither but before hit the issue it has to keep hlint messages (#1447)

**Comment by jneira** [comment] 2019-12-22 22:29
Hi, after last update to haskell-lsp, already used by hie, apply hlint hints is more reliable, @JRikken could you try again to check if it is fixed for you?

**Comment by jneira** [comment] 2020-01-01 01:16
@JRikken i am gonna close this one cause it probably was fixed when merging the hie-bios branch, feel free to reopen if it is not the case

**Closed by jneira** 2020-01-01 01:16 UTC
Labels: component: plugin, os: windows

**Comment by JRikken** [comment] 2020-01-06 12:28
@jneira , sorry for the late reply. Fetched the latest version today, these are the findings:

1. Indeed, the fix for #1447 worked, hlint output does no longer disappear on vscode

So, this time I tested with both vscode and atom 😄, the next points apply to both editors.

2. The spurious newlines are no longer inserted when applying (any) hlint recommendations
3. Applying the hlint recommendation to the string literal works as expected
4. Applying the hlint recommendation to the type signature does **not** work as expected (no change is visible, e.g. `(String)` should become `String`, but is not changed)

The output of "Haskell HIE (hiebugs)" in vscode gives:
```
2020-01-06 11:50:15.8883593 [ThreadId 37] - applyHint:apply=[("C:\\Users\\jrk\\AppData\\Local\\Temp\\haskell-lsp16724\\Lib.hs-00000-1300647511.hs:9:11: Warning: Redundant bracket\nFound:\n  (String)\nPerhaps:\n  String\n",[Replace {rtype = Expr, pos = SrcSpan {startLine = 9, startCol = 11, endLine = 9, endCol = 19}, subts = [("x",SrcSpan {startLine = 9, startCol = 12, endLine = 9, endCol = 18})], orig = "x"}])]
2020-01-06 11:50:15.9061904 [ThreadId 37] - applyHint:diff=WorkspaceEdit {_changes = Nothing, _documentChanges = Just (List [TextDocumentEdit {_textDocument = VersionedTextDocumentIdentifier {_uri = Uri {getUri = "file:///C:/Users/jrk/Desktop/OLD6/bugReport/hiebugs/src/Lib.hs"}, _version = Just 0}, _edits = List []}])}
2020-01-06 11:50:15.907188 [ThreadId 37] - applyOneCmd:file="c:\\Users\\jrk\\Desktop\\OLD6\\bugReport\\hiebugs\\src\\Lib.hs"
2020-01-06 11:50:15.907188 [ThreadId 37] - applyOneCmd:res=Right (WorkspaceEdit {_changes = Nothing, _documentChanges = Just (List [TextDocumentEdit {_textDocument = VersionedTextDocumentIdentifier {_uri = Uri {getUri = "file:///C:/Users/jrk/Desktop/OLD6/bugReport/hiebugs/src/Lib.hs"}, _version = Just 0}, _edits = List []}])})
```

It appears that the line / column numbers indicated on the first line are correct, however from the second line on the action notes `_changes = Nothing`?

**Comment by bubba** [comment] 2020-01-06 13:20
@JRikken somethings definitely going wrong! It could be the function we use to diff the changes between the hlint'ed file and the current file not handling that case. Is there a specific file that this always happens on?

**Comment by JRikken** [comment] 2020-01-06 13:39
😭 I started playing with the command-line versions of hlint & refactor (if I understood correctly, these are used as libraries for the linting / refactoring functionality of HIE?, using `hlint <file> --refactor --refactor-options="--inplace"`). This did appear to apply the hints correctly (both to type signature and string literal). However, this also changed the line endings in my test file from LF to CRLF (I am not certain if this is intended behavior, but I assume this is a bug on its own 🤔). 

After which, the spurious newline problem returned...

So after some further testing: 
- In CRLF-ended file
  - Using HIE and vscode
    - Applying hints to type signatures **does not work**
    - Applying hints to string literals **works**
    - Both apply actions cause a **single newline** to be inserted after **every single-line comment in the file**
  - Using `hlint <file> --refactor --refactor-options="--inplace"`
    - Applying hints to type signatures **works**
    - Applying hints to string literals **works**
    - Applying **any number of actions** cause a **single newline** to be inserted after **every single-line comment in the file**

- In LF-ended file
  - Using HIE and vscode
    - Applying hints to type signatures **does not work**
    - Applying hints to string literals **works**
    - **No spurious newlines are inserted**
  - Using `hlint <file> --refactor --refactor-options="--inplace"`
    - Applying hints to type signatures **works**
    - Applying hints to string literals **works**
    - **No spurious newlines are inserted**

My test file:
```Haskell
module Lib
    ( someFunc
    ) where

{- My Multiline -}

-- My Single line A
someFunc :: IO ()
someFunc = putStrLn myFunc

myFunc :: (String)
myFunc = ("Hello")

-- My single line B

```

I hope this helps pinpointing the location of the issue

**Comment by bubba** [comment] 2020-01-06 14:53
Those newlines being inserted in a CLRF file sound like an upstream issue with either hlint or apply-refact, you might want to open an issue with them

As for applying hints to type signatures not working in hie, that’s definitely us. I’ll create a new issue for it and take a look at it later this evening

Thanks for all the detailed reporting, this is extremely useful

**Comment by bubba** [comment] 2020-01-06 20:06
@JRikken this was caused by an upstream issue in hlint. I've opened a PR for it, hopefully it gets merged soon
