### ISSUE TITLE
HIE unresponsive with vim and atom

### ISSUE THREAD

**Issue by Arkemyr** [haskell/haskell-ide-engine#1397] opened 2019-09-27 19:10 UTC
I have vim[^1] set up with `LanguageClient-neovim` and HIE does not seem to respond, although it is running[^2].

```
VIM 8.1
GHC 8.6.4
HIE 0.10.0.0
macOS 10.15
```
Also:
```
apm  2.4.3
atom 1.40.1
atom-ide-ui 0.13.0
ide-haskell-hie 0.12.0
language-haskell 1.19.1
```

I am not savvy enough in vim to deduce how to pass hie-wrapper options (like where to log) through LanguageClient-neovim, so #1090 did not help me.

I tried to set it up with Atom, but it does not do anything? I specifically selected log to /tmp/hie.log but no log was produced 😢 A custom shell script hie-wrapper with all the flags on also does not produce any log file.

<details>
<summary>Trying things from the `LanguageClient_contextMenu`</summary>

1. Type Definition 
    ```
    [LC] timed out waiting on receive operation
    ```
2) Code Action
    ```
    [LC] timed out waiting on receive operation
    ```
3) Workspace Symbol
     ```
      [LC] [Error] haskell-lsp:no handler for. Object (fromList [("jsonrpc",String "2.0"),("params",Object (fromList [("query",String "")])),("method",String "workspace/symbol"),("id",Number 13.0)])
     ```
4) Rename
    ```
    [LC] timed out waiting on receive operation
    ```
5) Definition
    ```
    [LC] timed out waiting on receive operation
    ```
6) References
    ```
    [LC] timed out waiting on receive operation
    ```
7) Formatting
    ???
8) Range Formatting
    ???
9) Document Highlight
    ???
10) Signature Help
    ```
    [LC] [Error] haskell-lsp:no handler for. Object (fromList [("jsonrpc",String "2.0"),("param...acter",Number 4.0)]))])),("method",String "textDocument/signatureHelp"),("id",Number 5.0)])
    [LC] timed out waiting on receive operation
    ```
11) Hover
    ```
    [LC] timed out waiting on receive operation
    ```
12) Document Symbol
    ```
    [LC] timed out waiting on receive operation
    ```
13) Implementation
    ```
    [LC] [Error] haskell-lsp:no handler for. Object (fromList [("jsonrpc",String "2.0"),("param...er",Number 28.0)]))])),("method",String "textDocument/implementation"),("id",Number 10.0)])
    [LC] timed out waiting on receive operation
    ```

Maybe some of the timeots were in fact timeots of the previous operation, hard to say without log file.
</details>

<details>
<summary>My current vim settings</summary>

```
Plugin 'autozimu/LanguageClient-neovim'
set runtimepath+=~/.vim/bundle/LanguageClient-neovim
let g:LanguageClient_serverCommands = { 'haskell': ['hie-wrapper'] }
let g:LanguageClient_loggingFile = expand('~/.vim/LanguageClient.log')

nnoremap <F5> :call LanguageClient_contextMenu()<CR>
map <Leader>lk :call LanguageClient#textDocument_hover()<CR>
map <Leader>lg :call LanguageClient#textDocument_definition()<CR>
map <Leader>lr :call LanguageClient#textDocument_rename()<CR>
map <Leader>lf :call LanguageClient#textDocument_formatting()<CR>
map <Leader>lb :call LanguageClient#textDocument_references()<CR>
map <Leader>la :call LanguageClient#textDocument_codeAction()<CR>
map <Leader>ls :call LanguageClient#textDocument_documentSymbol()<CR>

hi link ALEError Error
hi Warning term=underline cterm=underline ctermfg=Yellow gui=undercurl guisp=Gold
hi link ALEWarning Warning
hi link ALEInfo SpellCap

let g:LanguageClient_rootMarkers = ['*.cabal', 'stack.yaml']
```

</details>

---
                                                                                                                         
[^1]: neovim does not solve the problem - I tried 😉   
[^2]: when I modified `LanguageClient_serverCommands` to `'haskell': ['hie-wrapper -l "someLogFileInVimFolder"']` it did explicitly say that no server was running for haskell, so I guess it was running otherwise. Also it spits out errors (when used wrong?) sometimes, eg with Workspace Symbol.

**Comment by fendor** [comment] 2019-09-27 19:51
While I can not help you with vim, I want to mention, that your HIE version is not up-to-date, so maybe upgrading fixes it.
You can also try to run the func-test-suite in hie and see if everything works as intended: `cabal v2-run test:func-test`, or `stack exec haskell-ide-engine:test:func-test`, assuming you built the test-suite before that. Dont forget to use the appropiate ghc version and supply the correct `--stack-yaml` flag!

**Comment by Arkemyr** [comment] 2019-10-08 23:08
Thanks @fendor, it took me a while but I am now living happily again in New Cabal land.

The integration with editors is still not smooth, but I believe that is not a fault of HIE 🙂

**Comment by jneira** [comment] 2019-11-21 07:15
@Arkemyr so could we close the issue?

**Closed** 2019-11-21 09:47 UTC
Labels: status: need confirmation
