### ISSUE TITLE
getCompletions: module not loaded

### ISSUE THREAD

**Issue by nponeccop** [haskell/haskell-ide-engine#406] opened 2017-12-12 23:21 UTC
On @wz1000 branch in Neovim LanguageClient I get:

```
2017-12-13 00:59:21.131379046 [ThreadId 8] - <--2--{"error":{"code":-32603,"message":"IdeError {ideCode = PluginError, ideMessage = \"getCompletions: \\\"module not loaded\\\"\", ideInfo = Null}"},"jsonrpc":"2.0","id":1}
```
and few of the errors of #369 and #390 

Neovim apparently doesn't react on `publishDiagnostics` messages from HIE. I'll investigate and keep you informed.

**Comment by nponeccop** [comment] 2017-12-15 07:30
It seems that the neovim LanguageClient switched to a Rust-based wrapper, so now nvim starts Python, Python starts Rust and Rust starts Haskell

The new version produces yet another set of errors :( E.g.

```
[Error] haskell-lsp:parse error. Object (fromList [("params",Object (fromList [("textDocument",Object (fromList [("version",Null),("languageId",String "haskell"),("text",String "m"),"uri",String "file:///home/andy/github/cubicaltt/foo.hs")]))])),("method",String "textDocument/didOpen"),("jsonrpc",String "2.0")]) "expected Int, encountered Null" `stack update` and install new haskell-lsp. Or check information on https://marketplace.visualstudio.com/items?itemName=xxxxxxxxxxxxxxx
```

**Comment by meck** [comment] 2017-12-18 00:39
I tracked this down [here](https://github.com/autozimu/LanguageClient-neovim/issues/213) the message dosen't show up using the latest rust wrapper. However autocomplete almost never works for me, still looking for the source of that problem...

**Comment by nponeccop** [comment] 2017-12-19 03:31
@meck yes I had to compile the binary manually due to https://github.com/autozimu/LanguageClient-neovim/issues/220 and now it works

**Comment by nponeccop** [comment] 2017-12-19 03:49
Works fine with current master fa3a4b12188412bbb86d3273d0c32c13674c2355 after all workarounds (related to neovim) applied.

**Comment by nponeccop** [comment] 2017-12-24 01:24
I ger the following in current neovim LanguageServer:
```
2017-12-24T02:34:44.249872242+02:00 ERROR languageclient::languageclient - Error", "method": "languageClient/omniComplete", "params": {"character": 11, "languag": "/home/andy/github/cubicaltt/Main.hs"}}. Error: Err(ErrorMessage { msg: "IdeEions: \\\"module not loaded\\\"\", ideInfo = Null}" })
2017-12-24T02:35:59.702235987+02:00 ERROR languageclient::languageclient - Error", "method": "languageClient/omniComplete", "params": {"character": 26, "languag": "/home/andy/github/cubicaltt/Main.hs"}}. Error: Err(ErrorMessage { msg: "IdeEions: \\\"module not loaded\\\"\", ideInfo = Null}" })
```

**Comment by soylens** [comment] 2018-02-03 03:07
Emacs lsp-haskell keeps reporting
```
Error from the Language Server: IdeError {ideCode = PluginError, ideMessage = "getSymbolAtPoint: \"module not loaded\"", ideInfo = Null} (Internal Error)
Error from the Language Server: IdeError {ideCode = PluginError, ideMessage = "getReferencesInDoc: \"module not loaded\"", ideInfo = Null} (Internal Error)
```
using emacs-mac 25.3
Is this a duplicate of this issue?
It seems to take some time loading all modules, also When I tested on windows. but usually it returns normal after a couple of seconds after hie starts. But here it takes rather long time, i've been waiting for minutes and it still reports this.

**Comment by Denommus** [comment] 2018-02-20 20:08
Also getting this on Emacs.

**Comment by Drezil** [comment] 2018-04-03 13:28
I think i cornered it down a bit in my yesod-project.

After startup completion (according to log) works. When i open up a new line & start insert-mode it replies with "[]", because i have not entered anything.

```
2018-04-03 15:05:57.68181 [ThreadId 4] - ---> {"jsonrpc":"2.0","method":"textDocument/completion","params":{"position":{"character":0,"line":16},"textDocument":{"uri":".....hs"}},"id":31}
2018-04-03 15:05:57.68271 [ThreadId 8] - reactor:got CompletionRequest:RequestMessage {_jsonrpc = "2.0", _id = IdInt 31, _method = TextDocumentCompletion, _params = TextDocumentPositionParams {_textDocument = TextDocumentIdentifier {_uri = Uri {getUri = "file:///media/remote/xxx/git/lerncenter/src/Foundation.hs"}}, _position = Position {_line = 16, _character = 0}}}
2018-04-03 15:05:57.755382 [ThreadId 5] - <--2--{"result":[],"jsonrpc":"2.0","id":31}
```

So far, so good.

As i type something seems to kick in an some linking-errors get pasted into the log (asynchronous without timestamp):

```
hie-8.2.2: /homes/xxx/.stack/snapshots/x86_64-linux/lts-11.2/8.2.2/lib/x86_64-linux-ghc-8.2.2/yaml-0.8.28-2bsQzcKBsMGIgZfDsXK13D/libHSyaml-0.8.28-2bsQzcKBsMGIgZfDsXK13D.a: unhandled ELF relocation(RelA) type 42

hie-8.2.2: /homes/xxx/.stack/snapshots/x86_64-linux/lts-11.2/8.2.2/lib/x86_64-linux-ghc-8.2.2/yaml-0.8.28-2bsQzcKBsMGIgZfDsXK13D/libHSyaml-0.8.28-2bsQzcKBsMGIgZfDsXK13D.a: unknown symbol `simple_document_start'
hie-8.2.2: /homes/xxx/.stack/snapshots/x86_64-linux/lts-11.2/8.2.2/lib/x86_64-linux-ghc-8.2.2/yaml-0.8.28-2bsQzcKBsMGIgZfDsXK13D/libHSyaml-0.8.28-2bsQzcKBsMGIgZfDsXK13D.a: unknown symbol `yamlzm0zi8zi28zm2bsQzzcKBsMGIgZZfDsXK13D_TextziLibyaml_zdfShowEvent_closure'
hie-8.2.2: /homes/xxx/.stack/snapshots/x86_64-linux/lts-11.2/8.2.2/lib/x86_64-linux-ghc-8.2.2/yaml-0.8.28-2bsQzcKBsMGIgZfDsXK13D/libHSyaml-0.8.28-2bsQzcKBsMGIgZfDsXK13D.a: unknown symbol `yamlzm0zi8zi28zm2bsQzzcKBsMGIgZZfDsXK13D_DataziYamlziInternal_CyclicIncludes_closure'
hie-8.2.2: /homes/xxx/.stack/snapshots/x86_64-linux/lts-11.2/8.2.2/lib/x86_64-linux-ghc-8.2.2/yaml-0.8.28-2bsQzcKBsMGIgZfDsXK13D/libHSyaml-0.8.28-2bsQzcKBsMGIgZfDsXK13D.a: unknown symbol `yamlzm0zi8zi28zm2bsQzzcKBsMGIgZZfDsXK13D_DataziYamlziInclude_zdszdfMonadResourceStateT0_closure'
hie-8.2.2: /homes/xxx/.stack/snapshots/x86_64-linux/lts-11.2/8.2.2/lib/x86_64-linux-ghc-8.2.2/yesod-1.6.0-IxJQuTAQ6H1J5Lb7EeoUeg/libHSyesod-1.6.0-IxJQuTAQ6H1J5Lb7EeoUeg.a: unknown symbol `yamlzm0zi8zi28zm2bsQzzcKBsMGIgZZfDsXK13D_DataziYamlziConfig_loadYamlSettings1_info'
hie-8.2.2: ^^ Could not load 'yesodzm1zi6zi0zmIxJQuTAQ6H1J5Lb7EeoUeg_YesodziDefaultziConfig2_configSettingsYml_closure', dependency unresolved. See top entry above.
```

Soon after that i get

```
2018-04-03 15:05:58.798922 [ThreadId 4] - ---> {"jsonrpc":"2.0","method":"textDocument/completion","params":{"position":{"character":7,"line":16},"textDocument":{"uri":"file:///media/remote/xxx/git/lerncenter/src/Foundation.hs"}},"id":50}
2018-04-03 15:05:58.827649 [ThreadId 7] - ghcDispatcher: top of loop
2018-04-03 15:05:58.83879 [ThreadId 8] - reactor:got CompletionRequest:RequestMessage {_jsonrpc = "2.0", _id = IdInt 50, _method = TextDocumentCompletion, _params = TextDocumentPositionParams {_textDocument = TextDocumentIdentifier {_uri = Uri {getUri = "file:///media/remote/xxx/git/lerncenter/src/Foundation.hs"}}, _position = Position {_line = 16, _character = 7}}}
2018-04-03 15:05:58.83906 [ThreadId 7] - got request with id: Nothing
2018-04-03 15:05:58.859869 [ThreadId 5] - <--2--{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///media/remote/xxx/git/lerncenter/src/Foundation.hs","diagnostics":[{"severity":1,"range":{"start":{"line":18,"character":0},"end":{"line":18,"character":0}},"source":"ghcmod","message":"/tmp/ghc-mod28155/Foundation28154-8.hs:19:1: error:\n    parse error (possibly incorrect indentation or mismatched brackets)"},{"severity":4,"range":{"start":{"line":76,"character":8},"end":{"line":78,"character":29}},"source":"hlint","message":"Use fromMaybe\nFound:\n  case appRoot $ appSettings app of\n    Nothing -> getApprootText guessApproot app req\n    Just root -> root\nWhy not:\n  (fromMaybe (getApprootText guessApproot app req)\n   (appRoot $ appSettings app))\n"},{"severity":4,"range":{"start":{"line":108,"character":18},"end":{"line":112,"character":21}},"source":"hlint","message":"Redundant $\nFound:\n  NavbarLeft $\n  MenuItem{menuItemLabel = \"Home\", menuItemRoute = HomeR,\n           menuItemAccessCallback = True}\nWhy not:\n  NavbarLeft\n  MenuItem{menuItemLabel = \"Home\", menuItemRoute = HomeR,\n           menuItemAccessCallback = True}\n"},{"severity":4,"range":{"start":{"line":113,"character":18},"end":{"line":117,"character":21}},"source":"hlint","message":"Redundant $\nFound:\n  NavbarLeft $\n  MenuItem{menuItemLabel = \"Profile\", menuItemRoute = ProfileR,\n           menuItemAccessCallback = isJust muser}\nWhy not:\n  NavbarLeft\n  MenuItem{menuItemLabel = \"Profile\", menuItemRoute = ProfileR,\n           menuItemAccessCallback = isJust muser}\n"},{"severity":4,"range":{"start":{"line":118,"character":18},"end":{"line":122,"character":21}},"source":"hlint","message":"Redundant $\nFound:\n  NavbarLeft $\n  MenuItem{menuItemLabel = \"Admin\", menuItemRoute = AdminR,\n           menuItemAccessCallback = madmin == Just True}\nWhy not:\n  NavbarLeft\n  MenuItem{menuItemLabel = \"Admin\", menuItemRoute = AdminR,\n           menuItemAccessCallback = madmin == Just True}\n"},{"severity":4,"range":{"start":{"line":123,"character":18},"end":{"line":127,"character":21}},"source":"hlint","message":"Redundant $\nFound:\n  NavbarRight $\n  MenuItem{menuItemLabel = \"Login\", menuItemRoute = AuthR LoginR,\n           menuItemAccessCallback = isNothing muser}\nWhy not:\n  NavbarRight\n  MenuItem{menuItemLabel = \"Login\", menuItemRoute = AuthR LoginR,\n           menuItemAccessCallback = isNothing muser}\n"},{"severity":4,"range":{"start":{"line":128,"character":18},"end":{"line":132,"character":21}},"source":"hlint","message":"Redundant $\nFound:\n  NavbarRight $\n  MenuItem{menuItemLabel = \"Logout\", menuItemRoute = AuthR LogoutR,\n           menuItemAccessCallback = isJust muser}\nWhy not:\n  NavbarRight\n  MenuItem{menuItemLabel = \"Logout\", menuItemRoute = AuthR LogoutR,\n           menuItemAccessCallback = isJust muser}\n"},{"severity":4,"range":{"start":{"line":236,"character":22},"end":{"line":236,"character":65}},"source":"hlint","message":"Use :\nFound:\n  [authOpenId Claimed []] ++ extraAuthPlugins\nWhy not:\n  authOpenId Claimed [] : extraAuthPlugins\n"},{"severity":4,"range":{"start":{"line":241,"character":22},"end":{"line":241,"character":58}},"source":"hlint","message":"Use <$>\nFound:\n  getYesod >>= return . getHttpManager\nWhy not:\n  getHttpManager <$> getYesod\n"}]}}
2018-04-03 15:05:58.860661 [ThreadId 11] - ideDispatcher:got request with id: IdInt 50
2018-04-03 15:05:58.861036 [ThreadId 7] - Processing request as version matches
2018-04-03 15:05:58.867426 [ThreadId 11] - ideDispatcher: top of loop
2018-04-03 15:05:58.867528 [ThreadId 5] - <--2--{"error":{"code":-32603,"message":"IdeError {ideCode = PluginError, ideMessage = \"getCompletions: \\\"module not loaded\\\"\", ideInfo = Null}"},"jsonrpc":"2.0","id":50}
```

and all subsequest calls to "getCompletions" error out with "module not loaded".

Is the linking-error responsible for unloading of some modules? Everything except the completion still seems to work.

I also wonder why he uses my global `.stack-work` instead of the project one because on startup he displays the correct project-directory (or is that hie-related and not project-related?):
```
2018-04-03 15:05:43.349333 [ThreadId 4] - run entered for HIE Version 0.1.0.0, Git revision 57b0d7d0ce2805a8ab3b68280b4fb7c8ef73c2e2 (1258 commits) x86_64 ghc-8.2.2
2018-04-03 15:05:43.350326 [ThreadId 4] - Current directory:/media/remote/xxx/git/lerncenter
haskell-lsp:Starting up server ...
2018-04-03 15:05:43.351397 [ThreadId 4] - ---> {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"completion":{"completionItem":{"commitCharactersSupport":null,"documentationFormat":null,"snippetSupport":true},"dynamicRegistration":null}}},"initializationOptions":null,"processId":28104,"rootPath":"/media/remote/xxx/git/lerncenter","rootUri":"file:///media/remote/xxx/git/lerncenter","trace":"off"},"id":7}
2018-04-03 15:05:43.35309 [ThreadId 4] - haskell-lsp:initializeRequestHandler: setting current dir to project root:/media/remote/xxx/git/lerncenter
2018-04-03 15:05:43.353857 [ThreadId 5] - <--2--{"result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"willSave":false,"willSaveWaitUntil":false,"save":{"includeText":false}},"hoverProvider":true,"completionProvider":{"resolveProvider":true,"triggerCharacters":["."]},"definitionProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"codeActionProvider":true,"documentFormattingProvider":true,"documentRangeFormattingProvider":true,"renameProvider":true,"executeCommandProvider":{"commands":["applyrefact:applyOne","hare:demote"]}}},"jsonrpc":"2.0","id":7}
```

hope that helps.. ;)

**Comment by Drezil** [comment] 2018-04-03 17:05
Ok. It was the ELF-Thing in yaml

after i fixed the stack.yaml in my yesod project by appending:
```
apply-ghc-options: everything
ghc-options:
  "yaml": -opta-Wa,-mrelax-relocations=no
```
and nuking `.stack-work` the error-message vanishes.

Now all completion-lookups look like:
```
2018-04-03 19:00:58.459153 [ThreadId 5] - <--2--{"result":[],"jsonrpc":"2.0","id":73}
```

But at least the module get loaded :)

I think this is the fault of yaml-0.8.28 when doing some C-compilations (ignoring the flags and using RelA 42) during building... but that is just a guess.

**Comment by jacobstern** [comment] 2018-04-09 03:16
I also had this error with a scaffolded Yesod project using GHC 8.2.2 on Ubuntu 17.10. I had to add these flags for several libraries in order for HIE to work:
```yaml
apply-ghc-options: everything
ghc-options:
  "yaml": -opta-Wa,-mrelax-relocations=no
  "cipher-aes": -opta-Wa,-mrelax-relocations=no
  "skein": -opta-Wa,-mrelax-relocations=no
```
I'm not sure where in the stack this problem might be originating but it doesn't appear to be specific to the `yaml` package.

**Comment by alanz** [comment] 2018-12-24 12:37
Is this still a problem?

**Comment by Drezil** [comment] 2018-12-24 14:31
I have not noticed it under 8.4.4 or 8.6 that I currently use.
Either those packages added those flags or some defaults changed or it was fixed with some ghc-issue.

**Closed** 2018-12-24 14:56 UTC
Labels: editor: neovim, os: linux

**Comment by MaskRay** [comment] 2018-12-24 18:18
>   "yaml": -opta-Wa,-mrelax-relocations=no

binutils obtained support for R_X86_64_GOTPCRELX in late 2015 and early 2016. If your toolchain was old, you probably need to update them.
