### ISSUE TITLE
Faster completion

### ISSUE THREAD

**Issue by nponeccop** [haskell/haskell-ide-engine#366] opened 2017-11-25 06:37 UTC
While exact criteria is hard to establish, current 2-4 seconds to complete an identifier or an import on i3-4004U CPU seems too slow to me to be useful. This type of slowness is inherited from ghc-mod, I think. So something should be done with the completion performance once HIE is feature-complete, as now people can type faster than complete.

**Comment by ggVGc** [comment] 2017-11-25 11:17
I'm not sure how much could be done here? There's already caching going on, which to me improves things a lot. But haskell is inherently a slow language to compile(well, not compared to C++...).
I wouldn't think it comes fomr ghc-mod, but rather from actual ghc. There might be something to be done by using ghc options?

**Comment by wz1000** [comment] 2017-11-25 12:06
To be honest, the completion system needs a complete rework. It is slow and buggy, and also can be a lot smarter(module and pragma completion, taking into account local definitions, whether it is a type or value completion etc.)
I suspect using a data structure like a prefix tree might also speed it up a lot, as currently it is O(n) in the number of symbols in scope(which can be huge if you have a lot of imports or import something like lens).
I am planning to get back into it next week after my finals, but there are a couple of higher priority issues that need to be tackled, like the separation of the compile service(which should also make almost all queries faster). So I will try to fix this issue in December, but would appreciate if anyone else would be willing to take a look.

**Comment by nponeccop** [comment] 2017-11-25 12:46
@ggVGc Completion speed doesn't depend on compilation speed in a perfect world :) You just return stale results from the previous compilation immediately instead of starting compilation and waiting for it to complete.

Also, ghc front-end isn't designed with incrementality in mind, and a lot can be done there to speed it up by avoiding repeated work.

**Comment by wz1000** [comment] 2017-11-25 13:11
@nponeccop @ggVGc yes, compilation speed shouldn't be the cause here as we are processing the cached compilation data. 

However, compilation does add a fair amount of sluggishness to HIE, because of the single threaded IDE service provider process, which is responsible for executing all requests and does so in a blocking manner. 

Requests that trigger recompilation are much slower than all other requests, so allowing requests to access stale/old compile data while the recompile is running in parallel should drastically drop most of the sluggishness and lag you encounter when you use it. This will be at the cost of some correctness as we are using old compile data, so requests with "side effects"(modifying the file etc.) would still have to wait for the compile to finish.

This is precisely what I mentioned I will be tackling above.

IIRC, something like this has already been put into place for the hover request by @alanz, but it could be generalized to work for most requests HIE processes.

**Comment by IvanMalison** [comment] 2018-03-24 05:17
@wz1000 Would you consider this issue fixed?

You mentioned the completion of local definitions (I just filed #503 for this); is that something that you are planning on working on?

**Comment by lorenzo** [comment] 2018-10-23 20:16
I think autocompletion is quite speedy now, so I'll close this issue as it seems dormant. Please leave a comment if you think this still needs more improvement.

**Closed by lorenzo** 2018-10-23 20:16 UTC
Labels: type: performance
