### ISSUE TITLE
Initial Release

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#82] opened 2015-11-18 06:30 UTC
I am keen to get an initial release out by end Nov, even if it is just of the plugin API so we can start writing plugins as things exposed by a tool, rather than somehing in HIE.

The things that need to be in it should be captured in https://github.com/haskell/haskell-ide-engine/milestones/P1:%20Must

Ideally any kind of IDE integration would be good too, but I know that that is the hardest part initially.

What all should be in there?

**Comment by cocreature** [comment] 2015-11-18 09:22
Imho we should have a somewhat stable protocol in there, I'm not a friend of backwards compatibilty at all costs, but we should at least have figured out the big picture of how it will look like, so that IDEs can start taking a look at it and implement it. Apart from that we should imho have at least one useful command working in an IDE (which will probably be emacs). I would go for ghc-mod type info, since I consider that to be one of the most important features. Most likely we will get all commands that require only a file and location at once which is even better, but I don't consider that a requirement for an initial release.

**Comment by gracjan** [comment] 2015-11-18 11:05
Emacs ide-mode won't be ready in any means of this word before Nov ends, so
it cannot be a point in the release.

I would love to start producing 'progress reports' and let people fetch git
version, use it a little, start hacking.

We should definitely start spreading the word. If a 'release' is a good
means for that I'm not sure. haskell-mode's last release was in spring and
there were plenty of opportunities to communicate about haskell-mode even
when not doing releases.

Note: to have release we need a written release procedure.

**Comment by alanz** [comment] 2015-11-18 11:09
I was not expecting emacs mode to be ready.

I think a release tailored at other devs, rather than users, to show that there is progress, and some kind of framework to drive integration and discussion.

**Comment by gracjan** [comment] 2015-11-18 11:27
Okay.

**Comment by IvanMalison** [comment] 2017-10-20 00:37
Has this still not happened?

**Comment by alanz** [comment] 2017-10-20 06:07
Waiting for a later version of ghc-mod to be published. 

At the moment hie uses a lot of stitched-together dependency packages, from git repos.

**Comment by nponeccop** [comment] 2017-12-19 04:33
Is this a duplicate of #328?

**Closed** 2018-12-24 11:44 UTC
