### ISSUE TITLE
The plugin tries to use stty on Windows 10

### ISSUE THREAD

**Issue by mrakgr** [haskell/haskell-ide-engine#1704] opened 2020-03-14 11:35 UTC
Very similar to [this bug](https://github.com/dramforever/vscode-ghc-simple/issues/53) for a different plugin. Here is the printout for Hie.

```
2020-03-14 12:31:18.295957 [ThreadId 3] - run entered for hie-wrapper(hie-wrapper) Version 1.2, Git revision d2b3237419694e07e45c4c77b86f96809effcf2c (3840 commits) x86_64 ghc-8.6.5
2020-03-14 12:31:18.2969558 [ThreadId 3] - Current directory:c:\purescript
2020-03-14 12:31:18.2969558 [ThreadId 3] - Operating system:mingw32
2020-03-14 12:31:18.2969558 [ThreadId 3] - args:["--lsp"]
2020-03-14 12:31:18.2989534 [ThreadId 3] - Cabal-Helper decided to use: ProjLocStackYaml {plStackYaml = "c:\\purescript\\stack.yaml"}
'stty' is not recognized as an internal or external command,
operable program or batch file.
'stty' is not recognized as an internal or external command,
operable program or batch file.
'stty' is not recognized as an internal or external command,
operable program or batch file.
'stty' is not recognized as an internal or external command,
operable program or batch file.
'stty' is not recognized as an internal or external command,
operable program or batch file.
2020-03-14 12:31:23.7925428 [ThreadId 3] - Module "c:\purescript\File.hs" is loaded by Cradle: Cradle {cradleRootDir = "C:\\purescript", cradleOptsProg = CradleAction: Other Stack}
2020-03-14 12:31:23.7925428 [ThreadId 3] - Cradle directory:C:\purescript
2020-03-14 12:31:23.7925428 [ThreadId 3] - Executing Stack GHC with args: --numeric-version
2020-03-14 12:31:24.3758618 [ThreadId 3] - Project GHC version:8.6.5
2020-03-14 12:31:24.3758618 [ThreadId 3] - hie exe candidates :["hie-8.6.5.exe","hie-8.6.exe","hie.exe"]
2020-03-14 12:31:24.3758618 [ThreadId 3] - found hie exe at:C:\Users\Marko\AppData\Roaming\local\bin\hie-8.6.5.exe
2020-03-14 12:31:24.3758618 [ThreadId 3] - args:["--lsp"]
2020-03-14 12:31:24.3758618 [ThreadId 3] - launching ....



2020-03-14 12:31:24.3878475 [ThreadId 3] - Run entered for HIE(hie-8.6.5.exe) Version 1.2, Git revision d2b3237419694e07e45c4c77b86f96809effcf2c (3840 commits) x86_64 ghc-8.6.5
2020-03-14 12:31:24.3888465 [ThreadId 3] - Operating as a LSP server on stdio
2020-03-14 12:31:24.3888465 [ThreadId 3] - Current directory:c:\purescript
2020-03-14 12:31:24.3888465 [ThreadId 3] - Operating system:mingw32
2020-03-14 12:31:24.3888465 [ThreadId 3] - args:["--lsp"]
2020-03-14 12:31:24.3918433 [ThreadId 3] - Cabal-Helper decided to use: ProjLocStackYaml {plStackYaml = "c:\\purescript\\stack.yaml"}
'stty' is not recognized as an internal or external command,
operable program or batch file.
'stty' is not recognized as an internal or external command,
operable program or batch file.
'stty' is not recognized as an internal or external command,
operable program or batch file.
'stty' is not recognized as an internal or external command,
operable program or batch file.
'stty' is not recognized as an internal or external command,
operable program or batch file.
2020-03-14 12:31:29.0554011 [ThreadId 3] - Module "c:\purescript\File.hs" is loaded by Cradle: Cradle {cradleRootDir = "C:\\purescript", cradleOptsProg = CradleAction: Other Stack}
2020-03-14 12:31:29.0554011 [ThreadId 3] - Executing Stack GHC with args: --numeric-version
2020-03-14 12:31:29.6227389 [ThreadId 36] - Executing Stack GHC with args: --print-libdir
Using hie version: Version 1.2, Git revision d2b3237419694e07e45c4c77b86f96809effcf2c (3840 commits) x86_64 ghc-8.6.5
2020-03-14 12:31:30.2170456 [ThreadId 42] - New cradle: C:\purescript\src\Language\PureScript.hs
Using hoogle db at: C:\Users\Marko\AppData\Roaming\hoogle\default-haskell-5.0.17.hoo
2020-03-14 12:31:30.2280328 [ThreadId 42] - Cabal-Helper decided to use: ProjLocStackYaml {plStackYaml = "C:\\purescript\\stack.yaml"}
'stty' is not recognized as an internal or external command,
operable program or batch file.
'stty' is not recognized as an internal or external command,
operable program or batch file.
'stty' is not recognized as an internal or external command,
operable program or batch file.
'stty' is not recognized as an internal or external command,
operable program or batch file.
'stty' is not recognized as an internal or external command,
operable program or batch file.
2020-03-14 12:31:34.9025778 [ThreadId 42] - Module "C:\purescript\src\Language\PureScript.hs" is loaded by Cradle: Cradle {cradleRootDir = "C:\\purescript", cradleOptsProg = CradleAction: Other Stack}
2020-03-14 12:31:34.9025778 [ThreadId 42] - Found cradle: Cradle {cradleRootDir = "C:\\purescript", cradleOptsProg = CradleAction: Other Stack}
'stty' is not recognized as an internal or external command,
operable program or batch file.
[1 of 5] Compiling CabalHelper.Shared.Common ( C:\\purescript\.stack-work\cabal-helper\CabalHelper\Shared\Common.hs, C:\\purescript\.stack-work\cabal-helper\CabalHelper\Shared\Common.o )
[2 of 5] Compiling CabalHelper.Shared.InterfaceTypes ( C:\\purescript\.stack-work\cabal-helper\CabalHelper\Shared\InterfaceTypes.hs, C:\\purescript\.stack-work\cabal-helper\CabalHelper\Shared\InterfaceTypes.o )
[3 of 5] Compiling CabalHelper.Runtime.Compat ( C:\\purescript\.stack-work\cabal-helper\CabalHelper\Runtime\Compat.hs, C:\\purescript\.stack-work\cabal-helper\CabalHelper\Runtime\Compat.o )
[4 of 5] Compiling CabalHelper.Runtime.HelperMain ( C:\\purescript\.stack-work\cabal-helper\CabalHelper\Runtime\HelperMain.hs, C:\\purescript\.stack-work\cabal-helper\CabalHelper\Runtime\HelperMain.o )
[5 of 5] Compiling Main             ( C:\\purescript\.stack-work\cabal-helper\CabalHelper\Runtime\Main.hs, C:\\purescript\.stack-work\cabal-helper\Main.o )
Linking C:\\purescript\\.stack-work\\cabal-helper\\cabal-helper.exe ...
2020-03-14 12:32:16.1554382 [ThreadId 74] - Cradle set succesfully
```

**Comment by mrakgr** [comment] 2020-03-14 12:29
I thought it did not, but it seems the Hie plugin does in fact work despite the errors unlike the other one.

**Comment by jneira** [comment] 2020-03-14 12:58
Yeah, it only clutters the log. It is a `stack` specific bug and hie triggers `stack` executions to configure and get info from the project.
See  https://github.com/haskell/haskell-ide-engine/issues/1428 for more context and a workaround.
I will close as duplicate of #1428 if you dont mind.

**Closed** 2020-03-14 15:32 UTC
