### ISSUE TITLE
applyHint doesn't support CRLF files

### ISSUE THREAD

**Issue by soylens** [haskell/haskell-ide-engine#396] opened 2017-12-09 17:38 UTC
Applying HLint suggestions malfunctions. Logging shows that `applyHint`'s output is malfunctioning.
Related:https://github.com/alanz/vscode-hie-server/issues/33

**Comment by soylens** [comment] 2017-12-10 02:59
Likely a problem with vsCode Integration

**Comment by soylens** [comment] 2017-12-11 16:04
Logging shows that `applyHint`'s output is malfunctioning, which leads us back here

**Comment by soylens** [comment] 2017-12-11 16:05
See https://gist.github.com/soylens/0a790bf1c719a829d7c3def391ec2bf2

**Comment by nponeccop** [comment] 2017-12-12 01:36
Note that the `hie` of @soylens is also affected by the `%3a` issue. A fix for which exists https://github.com/alanz/haskell-lsp/pull/63 but not yet merged in `haskell-lsp` which is a dependency of `hie`. I can create a fork of `hie` which uses the patched `haskell-lsp` so we can see if it helps.

**Comment by soylens** [comment] 2017-12-12 12:07
what has been the reason to delay the merge? is something failing with `wz1000's async stuff`?

**Comment by soylens** [comment] 2017-12-12 13:09
so I cloned myself a HIE source and added ```haskell
liftIO $ logm $ "applyHint:commands=" ++ show commands
```
the results have been inserted to the partial log file("(partial)hie.log" L24).
the command doesnt seem to contain any problems, which (hopefully) lets us locate the problem on the line```haskell
appliedFile <- liftIO $ applyRefactorings (unPos <$> mpos) commands fp
```
which is either a problem of HIE or apply-refact's `applyRefactorings`

**Comment by nponeccop** [comment] 2017-12-12 20:02
> is something failing with wz1000's async stuff?

The @wz1000 PR was not ready until today: https://github.com/haskell/haskell-ide-engine/pull/403

**Comment by soylens** [comment] 2017-12-13 03:07
It could also be apply-refact that malfunctions

**Comment by soylens** [comment] 2017-12-16 15:35
@nponeccop Do you have any idea to this problem?
I recompiled with ghc8.2.2 and those udpated git repos but it still is there, i

**Comment by nponeccop** [comment] 2017-12-16 21:31
We should ask the authors. Also, can you check that `%3a` is fixed?

**Comment by soylens** [comment] 2017-12-17 13:38
It didnt when I built yesterday. Per what you said, and it holds for now, the fix for `%3a` is yet still not merged.

**Comment by soylens** [comment] 2017-12-17 13:44
With the newest version, the parts of applyHints didnt change(as expected for the recent updates didnt touch these parts), so I wouldnt bother typing in the same thing again. Although some new DocumentHeight info emerge, I wouldnt take them as related to this issue.

**Comment by soylens** [comment] 2017-12-17 15:05
Im building with the version pulled at UTC+8 23:00 17.Dec

**Comment by soylens** [comment] 2017-12-17 15:08
BTW why not use resolver set as ghc-*.*.*, using nightly builds constantly creating minor different version changes of the same package in different snapshots

**Comment by nponeccop** [comment] 2017-12-17 15:30
> the fix for %3a is not merged.

https://github.com/haskell/haskell-ide-engine/pull/403 was supposed to fix `3a` without the need for 
https://github.com/alanz/haskell-lsp/pull/63 . Do `%3a` problems still happen?

> why not use resolver set as ghc-*.*.*

Because we want to avoid daily changes of snapshots. Stability helps with reproduction of bugs.

**Comment by soylens** [comment] 2017-12-17 15:36
well, first, YES, `%3a` is still here with me.
And BTW It seems that THIS issue with applying Hints is actually caused by `makeDiffResult`
For I eventually realized to print the `appliedFile`

**Comment by soylens** [comment] 2017-12-17 15:41
```
2017-12-17 23:33:27.5120696 [ThreadId 6] - applyHint:ideas=[C:\Users\whain\AppData\Local\Temp\ghc-mod10018\secondTrouble10016-1.hs:7:13: Warning: Use foldl1
Found:
  foldl lcm (head a) (tail a)
Why not:
  foldl1 lcm a
]
2017-12-17 23:33:27.5170691 [ThreadId 6] - applyHint:commands=[("C:\\Users\\whain\\AppData\\Local\\Temp\\ghc-mod10018\\secondTrouble10016-1.hs:7:13: Warning: Use foldl1\nFound:\n  foldl lcm (head a) (tail a)\nWhy not:\n  foldl1 lcm a\n",[Replace {rtype = Expr, pos = SrcSpan {startLine = 7, startCol = 13, endLine = 7, endCol = 40}, subts = [("f",SrcSpan {startLine = 7, startCol = 19, endLine = 7, endCol = 22}),("x",SrcSpan {startLine = 7, startCol = 29, endLine = 7, endCol = 30})], orig = "foldl1 f x"}])]
2017-12-17 23:33:27.5280687 [ThreadId 6] - applyHint:appliedFile="main :: IO()\n\nfuna :: Int -> Int\n\nmain = do\n    let a = [funa 1,funb 2,func 3,fund 4]\n    let l = foldl1 lcm a\n    putStrLn $ (show :: Int -> String) l\n    return ()\n\nfunb :: Int -> Int\nfunc :: Int -> Int\n\nfund :: Int -> Int\n\nfuna _ = 1\nfunb _ = 2\nfunc _ = 3\nfund _ = 4\n"
2017-12-17 23:33:27.545068 [ThreadId 6] - applyHint:diff=WorkspaceEdit (something screws up)
```
so there you go, I think this would help

**Comment by nponeccop** [comment] 2017-12-17 15:44
So `appliedFile` is correct, but you use VSCode and the result there is wrong.

**Comment by soylens** [comment] 2017-12-17 15:50
Yea, I havnt really read the entire LSP details, but according to my logs, I believe that these things here are packed into a `WorkspaceEdit` and then passed to VS Code. And it seems the diff results, from which the `WorkspaceEdit` is genereated, are mistaken.

**Comment by soylens** [comment] 2017-12-17 16:00
It's midnight here, imanna sleep and be looking at these in the afternoon.

**Comment by soylens** [comment] 2017-12-18 11:52
Confirmed that this is caused by incorrect handling on line endings.
Regardlessly of the settings of VS Code, HIE's linting results are always `\\n`, leading to mistaken diff results.
So the linting only works correctly with UNIX line endings, and the `\\r`s are the cause of missing lines.

**Comment by soylens** [comment] 2017-12-19 11:11
Actually I think we can just add `liftM (T.filter (/='\r')) $` to the diff parts cuz VS Code handles EOL converting

**Comment by soylens** [comment] 2017-12-19 11:31
It doesnt seem to work though. I rebuilt HIE with updated code but nothing changed. HIE doesnt even say that the build is dirty.
Makes me think. I tested the readFiles(Prelude and Data.Text.IO) in GHCi, and it shows that the EOL is handled automatically, then what is causing this?

**Comment by soylens** [comment] 2017-12-19 12:44
My trackdown goes down to a ghc-mod temp directory, in which the `\r\n` is parsed into `\n\n`

**Comment by nponeccop** [comment] 2017-12-19 14:55
I think the long term solution is to properly support all separators everywhere instead of adhoc replacement of `\n` with `\r\n`. However we may want a quick hotfix for now. Any thoughts @alanz ?

**Comment by alanz** [comment] 2018-12-24 12:34
See alos #729

**Comment by jneira** [comment] 2019-12-29 23:09
I think this should be fixed by https://github.com/alanz/haskell-lsp/pull/208
@soylens feel free to reopen if you continue experiencing it

**Closed by jneira** 2019-12-29 23:09 UTC
