### ISSUE TITLE
Disappearing Hlint output in vscode

### ISSUE THREAD

**Issue by JRikken** [haskell/haskell-ide-engine#1447] opened 2019-11-11 09:57 UTC
Hi, I ran into an issue with HIE + VScode. 

## Issue
Hlint indicates some improvements in the code, and they are highlighted as expected, but as soon as typchecking finishes, the Hlint indications disappear and the "Problems" pane shows "No problems". 

## Tested
I have installed the editor plugins for Atom as well (without altering the HIE installation) and here the hlint indications are shown as expected (both in the code, as in the "diagnostics" pane) so it seems to me that the problem lies somewhere in the integration between HIE + VScode, which feels strange because as far as I know they are both LSP based? 

## Versions
- stack: 2.1.3 with LTS 14.12 & GHC 8.6.5 
- HIE version: hie-8.6.5; version 0.13.0.0. 
- OS: Windows 10 x86_64

**Comment by fendor** [comment] 2019-11-11 10:10
Thanks for the detailed report!
Duplicate of #1441

**Comment by patrickaldis** [comment] 2019-11-20 09:22
Can confirm I have the same problem on hie-8.4.3 v0.13.0.0, Windows 10, GHC 8.4.3, latest vscode

**Comment by tuomohopia** [comment] 2019-11-27 23:52
I'm running into this as well, with the same setup as the author of this issue. Any workarounds for now, like prolong the display time with some VSCode configuration setting?

**Comment by fendor** [comment] 2019-12-19 12:22
@jneira Is this issue fixed by the haskell-lsp udpates? Are the haskell-lsp changes already in master?

**Comment by jneira** [comment] 2019-12-19 13:21
It is fixed with haskell-lsp-0.19 which afaik can be only used by the hie-bios branch (due to other changes to vfs)
In fact my change over file uris and the fixes to vfs would fix it separately but including the first one would need a haskell-lsp-0.18.1 to use with actual hie master
As hie-bios will be merged soon it is not needed though.

**Closed** 2019-12-20 20:50 UTC
Labels: component: plugin, editor: vscode, os: windows
