### ISSUE TITLE
Visual Studio Code support

### ISSUE THREAD

**Issue by jason-johnson** [haskell/haskell-ide-engine#217] opened 2017-01-04 20:32 UTC
Visual Studio Code allows one to add language support by creating a [language server](https://code.visualstudio.com/docs/extensions/example-language-server).  It seems that this project would be a perfect fit for that and could provide a cross-platform, full featured IDE with a lot less effort.

**Comment by alanz** [comment] 2017-01-04 20:40
Duplicate of https://github.com/haskell/haskell-ide-engine/issues/213

**Closed by alanz** 2017-01-04 20:40 UTC
