### ISSUE TITLE
Formatting Document adds blank lines to CRLF separated files

### ISSUE THREAD

**Issue by soylens** [haskell/haskell-ide-engine#397] opened 2017-12-09 18:02 UTC
Using with VS code Integration
Each time I do the Format Document, a blank line is added between the neighboring 2 lines(including the blank lines previously inserted during the same process)

**Comment by lspitzner** [comment] 2017-12-09 18:37
most likely duplicate of #306.

**Comment by soylens** [comment] 2017-12-10 02:32
This is likely a problem with vsCode Integration

**Comment by soylens** [comment] 2017-12-17 15:58
@lspitzner 
Most likely not. My issue works like this
1. Blank lines added between every 2 line, regardlessly if they are empty
2. if i'm formatting the entire doc,
            replace the whole doc
   if i'm formatting selection
            replace the selected parts with THE SAME LINES OF the file added blank lines
So I end up with code from somewhere entirely else jumping into my selection and those i selected vanished

**Comment by nponeccop** [comment] 2017-12-17 16:03
Can you check the line endings in your files? Does this issue happen with both DOS (CR LF aka `0x0A 0x0D`) and Unix (LF aka `0x0D`) line endings?

**Comment by lspitzner** [comment] 2017-12-17 16:17
@soylens that sounds bad indeed. 2) almost sounds like it deserves a separate issue.

**Comment by soylens** [comment] 2017-12-18 11:53
@nponeccop Yup confirmed. HIE only work with LF EOLs.

**Comment by soylens** [comment] 2017-12-18 12:13
@nponeccop Yup confirmed. HIE only work with LF EOLs because according to the Haskell standards, LF should be used, but however causes problem when doing diffs with files with CRLF EOLs

**Comment by nponeccop** [comment] 2017-12-18 23:16
Haskell standards are largely irrelevant because we must support whatever GHC supports. And it works with CRLF/Windows lines just fine

**Comment by alanz** [comment] 2018-12-24 12:35
See also #729

**Comment by jneira** [comment] 2019-12-29 23:14
This one could be fixed  by https://github.com/alanz/haskell-lsp/pull/208 (like #729)
@soylens feel free to reopen if you continue experiencing it

**Closed by jneira** 2019-12-29 23:14 UTC
