### ISSUE TITLE
Go To Definition opens wrong file

### ISSUE THREAD

**Issue by AlexeyRaga** [haskell/haskell-ide-engine#279] opened 2017-08-11 10:48 UTC
Go To Definition opens a file with a weird name

![weird-tab](https://user-images.githubusercontent.com/1394391/29210292-3a7ab94e-7ed6-11e7-95d1-f8292ea3c9c7.gif)

**Comment by wz1000** [comment] 2017-08-11 11:18
I can't reproduce this. Which version of HIE are you using? Can you try the latest one from https://github.com/haskell/haskell-ide-engine

**Comment by AlexeyRaga** [comment] 2017-08-11 22:28
Strange. I am using VSCode 1.15.0 and the `wz1000\cleanup` branch of HIE (latest commit)

**Comment by wz1000** [comment] 2017-08-12 03:07
The cleanup branch has been merged into haskell/HIE:master. If it is not solved in that, I will try to implement a more robust solution for this.

BTW, which OS are you running HIE on?

**Comment by AlexeyRaga** [comment] 2017-08-12 07:04
I am running it on MacOS

**Comment by nebtrx** [comment] 2017-08-20 03:26
I'm having the same issue, I can confirm. I'm on the latest version as well. BTW, excelent job with this 🤘😎

**Comment by wz1000** [comment] 2017-08-20 05:19
@AlexeyRaga @nebtrx can you confirm if https://github.com/wz1000/haskell-ide-engine/commit/1f77505d61383ab4642d940c8d2c85e7bdfb64b9 solves your issue?

**Comment by AlexeyRaga** [comment] 2017-08-20 05:32
@wz1000 Looks like it does fix this issue, I cannot reproduce it anymore so far.

**Comment by nebtrx** [comment] 2017-08-20 07:57
@AlexeyRaga @wz1000 Confirmed! The issue disappeared!

**Closed** 2017-08-20 20:13 UTC
