### ISSUE TITLE
cabal-helper build fails

### ISSUE THREAD

**Issue by Nostradamos** [haskell/haskell-ide-engine#372] opened 2017-11-26 13:16 UTC
Cloned latest commit (6f46f1a62cae837bf4c3d317fadbd8c93539fb40)
but `stack install` fails on this error:
```
    Configuring foundation-0.0.13...
    Building foundation-0.0.13...
    Preprocessing library foundation-0.0.13...
    /usr/bin/ld: .stack-work/dist/x86_64-linux-tinfo6-nopie/Cabal-1.24.2.0/build/Foundation/System/Bindings/Posix_hsc_make.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
    /usr/bin/ld: final link failed: Nonrepresentable section on output
    collect2: Fehler: ld gab 1 als Ende-Status zurück
    linking .stack-work/dist/x86_64-linux-tinfo6-nopie/Cabal-1.24.2.0/build/Foundation/System/Bindings/Posix_hsc_make.o failed (exit code 1)
    command was: /usr/bin/gcc .stack-work/dist/x86_64-linux-tinfo6-nopie/Cabal-1.24.2.0/build/Foundation/System/Bindings/Posix_hsc_make.o .stack-work/dist/x86_64-linux-tinfo6-nopie/Cabal-1.24.2.0/build/Foundation/System/Bindings/Posix_hsc_utils.o -o .stack-work/dist/x86_64-linux-tinfo6-nopie/Cabal-1.24.2.0/build/Foundation/System/Bindings/Posix_hsc_make -fno-PIE -fno-stack-protector -L/home/kerle/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.2/lib/ghc-8.0.2/base-4.9.1.0 -Wl,-R,/home/kerle/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.2/lib/ghc-8.0.2/base-4.9.1.0 -L/home/kerle/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.2/lib/ghc-8.0.2/integer-gmp-1.0.0.1 -Wl,-R,/home/kerle/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.2/lib/ghc-8.0.2/integer-gmp-1.0.0.1 -lgmp -L/home/kerle/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.2/lib/ghc-8.0.2/ghc-prim-0.5.0.0 -Wl,-R,/home/kerle/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.2/lib/ghc-8.0.2/ghc-prim-0.5.0.0 -L/home/kerle/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.2/lib/ghc-8.0.2/rts -Wl,-R,/home/kerle/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.2/lib/ghc-8.0.2/rts -lm -lrt -ldl -lpthread


--  While building package clock-0.7.2 using:
      /home/kerle/.stack/setup-exe-cache/x86_64-linux-tinfo6-nopie/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux-tinfo6-nopie/Cabal-1.24.2.0 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/kerle/Apps/haskell-ide-engine/.stack-work/logs/clock-0.7.2.log

    Configuring clock-0.7.2...
    Building clock-0.7.2...
    Preprocessing library clock-0.7.2...
    /tmp/stack7046/clock-0.7.2/Clock.hsc:44:0: Warnung: »hsc_alignment« redefiniert
    /tmp/stack7046/clock-0.7.2/In file included from .stack-work/dist/x86_64-linux-tinfo6-nopie/Cabal-1.24.2.0/build/System/Clock_hsc_make.c:1:0:
    /home/kerle/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.2/lib/ghc-8.0.2/template-hsc.h:88:0: Anmerkung: dies ist die Stelle der vorherigen Definition
     #define hsc_alignment(t...) \
     
    /usr/bin/ld: .stack-work/dist/x86_64-linux-tinfo6-nopie/Cabal-1.24.2.0/build/System/Clock_hsc_make.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
    /usr/bin/ld: final link failed: Nonrepresentable section on output
    collect2: Fehler: ld gab 1 als Ende-Status zurück
    linking .stack-work/dist/x86_64-linux-tinfo6-nopie/Cabal-1.24.2.0/build/System/Clock_hsc_make.o failed (exit code 1)
    command was: /usr/bin/gcc .stack-work/dist/x86_64-linux-tinfo6-nopie/Cabal-1.24.2.0/build/System/Clock_hsc_make.o .stack-work/dist/x86_64-linux-tinfo6-nopie/Cabal-1.24.2.0/build/System/Clock_hsc_utils.o -o .stack-work/dist/x86_64-linux-tinfo6-nopie/Cabal-1.24.2.0/build/System/Clock_hsc_make -fno-PIE -fno-stack-protector -L/home/kerle/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.2/lib/ghc-8.0.2/base-4.9.1.0 -Wl,-R,/home/kerle/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.2/lib/ghc-8.0.2/base-4.9.1.0 -L/home/kerle/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.2/lib/ghc-8.0.2/integer-gmp-1.0.0.1 -Wl,-R,/home/kerle/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.2/lib/ghc-8.0.2/integer-gmp-1.0.0.1 -lgmp -L/home/kerle/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.2/lib/ghc-8.0.2/ghc-prim-0.5.0.0 -Wl,-R,/home/kerle/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.2/lib/ghc-8.0.2/ghc-prim-0.5.0.0 -L/home/kerle/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.2/lib/ghc-8.0.2/rts -Wl,-R,/home/kerle/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.2/lib/ghc-8.0.2/rts -lm -lrt -ldl -lpthread
```

**Comment by alanz** [comment] 2017-11-27 06:33
What operating system are you on?

**Comment by falsandtru** [comment] 2017-11-28 17:15
I got a similar error these last few days.

```
$ stack --version
Version 1.5.1, Git revision 600c1f01435a10d127938709556c1682ecfd694e (4861 commits) x86_64 hpack-0.17.1
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.2
$ stack install
Cabal file warning in /home/user/Development/haskell-ide-engine/.stack-work/downloaded/i8_9JFxZIgdz/cabal-helper.cabal: Unknown fields: scope (line 96)
Fields allowed in this section:
    main-is, buildable, build-tools, build-depends, cpp-options,
    cc-options, ld-options, pkgconfig-depends, frameworks,
    extra-framework-dirs, c-sources, js-sources, default-language,
    other-languages, default-extensions, other-extensions, extensions,
    extra-libraries, extra-ghci-libraries, extra-lib-dirs, includes,
    install-includes, include-dirs, hs-source-dirs, other-modules,
    ghc-prof-options, ghcjs-prof-options, ghc-shared-options,
    ghcjs-shared-options, ghc-options, ghcjs-options, jhc-options,
    hugs-options, nhc98-options
cabal-helper-0.8.0.0: configure (lib + exe)
monad-memo-0.4.1: configure
monad-memo-0.4.1: build
syz-0.2.0.0: configure
syz-0.2.0.0: build
yi-rope-0.10: configure
yi-rope-0.10: build
syz-0.2.0.0: copy/register
monad-memo-0.4.1: copy/register
yi-rope-0.10: copy/register
Progress: 4/22
--  While building package cabal-helper-0.8.0.0 using:
      /home/user/Development/haskell-ide-engine/.stack-work/downloaded/i8_9JFxZIgdz/.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0/setup/setup --builddir=.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0 configure --with-ghc=/home/user/.stack/programs/x86_64-linux/ghc-nopie-8.0.2/bin/ghc --with-ghc-pkg=/home/user/.stack/programs/x86_64-linux/ghc-nopie-8.0.2/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/home/user/.stack/snapshots/x86_64-linux-nopie/nightly-2017-07-25/8.0.2/pkgdb --package-db=/home/user/Development/haskell-ide-engine/.stack-work/install/x86_64-linux-nopie/nightly-2017-07-25/8.0.2/pkgdb --libdir=/home/user/Development/haskell-ide-engine/.stack-work/install/x86_64-linux-nopie/nightly-2017-07-25/8.0.2/lib --bindir=/home/user/Development/haskell-ide-engine/.stack-work/install/x86_64-linux-nopie/nightly-2017-07-25/8.0.2/bin --datadir=/home/user/Development/haskell-ide-engine/.stack-work/install/x86_64-linux-nopie/nightly-2017-07-25/8.0.2/share --libexecdir=/home/user/Development/haskell-ide-engine/.stack-work/install/x86_64-linux-nopie/nightly-2017-07-25/8.0.2/libexec --sysconfdir=/home/user/Development/haskell-ide-engine/.stack-work/install/x86_64-linux-nopie/nightly-2017-07-25/8.0.2/etc --docdir=/home/user/Development/haskell-ide-engine/.stack-work/install/x86_64-linux-nopie/nightly-2017-07-25/8.0.2/doc/cabal-helper-0.8.0.0 --htmldir=/home/user/Development/haskell-ide-engine/.stack-work/install/x86_64-linux-nopie/nightly-2017-07-25/8.0.2/doc/cabal-helper-0.8.0.0 --haddockdir=/home/user/Development/haskell-ide-engine/.stack-work/install/x86_64-linux-nopie/nightly-2017-07-25/8.0.2/doc/cabal-helper-0.8.0.0 --dependency=Cabal=Cabal-1.24.2.0 --dependency=base=base-4.9.1.0 --dependency=bytestring=bytestring-0.10.8.1 --dependency=containers=containers-0.5.7.1 --dependency=directory=directory-1.3.0.0 --dependency=exceptions=exceptions-0.8.3-ADEDRATtUrMK1JW4zMQ9U --dependency=filepath=filepath-1.4.1.1 --dependency=ghc-prim=ghc-prim-0.5.0.0 --dependency=mtl=mtl-2.2.1-BLKBelFsPB3BoFeSWSOYj6 --dependency=process=process-1.4.3.0 --dependency=semigroupoids=semigroupoids-5.2-8RI6HtO1LKLE496qmzB9Po --dependency=template-haskell=template-haskell-2.11.1.0 --dependency=temporary=temporary-1.2.1-74wXvKX6cPmH7eOQxlSWZQ --dependency=transformers=transformers-0.5.2.0 --dependency=unix=unix-2.7.2.1 --dependency=unix-compat=unix-compat-0.4.3.1-Ausmw6d7KIwA7sl52mzqxC --dependency=utf8-string=utf8-string-1.0.1.1-1DpjxLeTvGg7ttZZojxJR5 --enable-tests --enable-benchmarks
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/user/Development/haskell-ide-engine/.stack-work/logs/cabal-helper-0.8.0.0.log

    Warning: cabal-helper.cabal: Unknown fields: scope (line 96)
    Fields allowed in this section:
    main-is, buildable, build-tools, build-depends, cpp-options,
    cc-options, ld-options, pkgconfig-depends, frameworks,
    extra-framework-dirs, c-sources, js-sources, default-language,
    other-languages, default-extensions, other-extensions, extensions,
    extra-libraries, extra-ghci-libraries, extra-lib-dirs, includes,
    install-includes, include-dirs, hs-source-dirs, other-modules,
    ghc-prof-options, ghcjs-prof-options, ghc-shared-options,
    ghcjs-shared-options, ghc-options, ghcjs-options, jhc-options,
    hugs-options, nhc98-options
    Configuring cabal-helper-0.8.0.0...
    setup: The program 'cabal' is required but it could not be found.
```

I resolved this by using lts-9.14.

```
$ git diff
diff --git a/stack.yaml b/stack.yaml
index 3c2a9be..ced49c9 100644
--- a/stack.yaml
+++ b/stack.yaml
@@ -1,4 +1,4 @@
-resolver: nightly-2017-07-25
+resolver: lts-9.14
 packages:
 - .
 - hie-apply-refact
```

**Comment by nponeccop** [comment] 2017-11-28 21:08
@Nostradamos can you try building now and confirm that the issue is fixed?

**Comment by juho-p** [comment] 2017-12-03 12:36
I also had issues with installing using `stack install`. The following error message was produced:

    --  While building package ghc-mod-5.9.0.0 using:
          /usr/bin/ghc --make -odir /home/juho/build/haskell-ide-engine/.stack-work/downloaded/0ctJ1Puyy1Om/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup -hidir /home/juho/build/haskell-ide-engine/.stack-work/downloaded/0ctJ1Puyy1Om/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup -i -i. -package=Cabal-1.24.2.0 -clear-package-db -global-package-db -package-db=/home/juho/.stack/snapshots/x86_64-linux/lts-9.14/8.0.2/pkgdb /home/juho/build/haskell-ide-engine/.stack-work/downloaded/0ctJ1Puyy1Om/Setup.hs -o /home/juho/build/haskell-ide-engine/.stack-work/downloaded/0ctJ1Puyy1Om/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/setup
        Process exited with code: ExitFailure 1
        Logs have been written to: /home/juho/build/haskell-ide-engine/.stack-work/logs/ghc-mod-5.9.0.0.log

        
        /home/juho/build/haskell-ide-engine/.stack-work/downloaded/0ctJ1Puyy1Om/Setup.hs:4:2: error:
             error: #error Your version of cabal-install does not seem to support the 'custom-setup' section. Please see https://github.com/DanielG/ghc-mod/wiki/Installing#checking-and-installing-prerequisites for instrutions on how to upgrade. It is also possible that you forgot to install cabal-doctest before running Setup.hs
             #error \
              ^~~~~
        `gcc' failed in phase `C pre-processor'. (Exit code: 1)

I got around this by running `stack install cabal-doctest` before `stack install`. I'm not sure if this was a problem related to haskell-ide-engine build configuration or just my local haskell-installation problem, since I'm pretty new to Haskell and Stack. But maybe it would be a good idea to update README to say cabal-docktest must be installed beforehands, if it really is?

**Comment by nponeccop** [comment] 2017-12-03 20:01
It isn't normally required. But our circleci.yml uses a different approach due to caching needs. Maybe @alanz could test a clean build with instructions from Readme and see if the problem can be reproduced.

Also, @juho-p, what does `stack --version` show? If it's less than 1.5.1 you need a newer stack.

**Comment by juho-p** [comment] 2017-12-03 20:08
`stack --version` shows `Version 1.1.2 x86_64 hpack-0.14.1`, which I guess is too old? Even with this stack version, `hie` seems to work at least for my basic use case, which is very nice.

**Comment by alanz** [comment] 2017-12-03 20:13
What I have found is that stack does not always deal gracefully with git-style dependencies and sub-projects.

So if my build goes funny like that, I will first do

```bash
$ find . -iname ".stack-work" | xargs rm -fr
```

From the main project directory

**Comment by falsandtru** [comment] 2017-12-03 20:22
I've also run `$ rm -rf .stack-work`, before installing.

**Comment by alanz** [comment] 2017-12-03 20:26
You need to do the recursive one. Each subproject has a .stack-work too

**Comment by falsandtru** [comment] 2017-12-03 20:29
Indeed.

**Comment by mgsloan** [comment] 2017-12-04 13:12
`stack clean --full` essentially does recursive removal of all the .stack-work folders.  Stack 1.6.1 should be released in a week, and IIRC, it has some fixes that improve git support

**Comment by mkunikow** [comment] 2017-12-07 22:27
Hi,
I have the same issue and stack clean --full does not help.

```
>>> stack --version                                                                                                                                                                                                                                             (1) (master+1101) 23:22:49 
Version 1.6.1, Git revision f25811329bbc40b0c21053a8160c56f923e1201b (5435 commits) x86_64 hpack-0.20.0
```

```
>>> uname -a                                                                                                                                                                                                                                                        (master+1101) 23:25:46 
Linux nuc 4.10.0-40-generic #44~16.04.1-Ubuntu SMP Thu Nov 9 15:37:44 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
```
--  While building custom Setup.hs for package cabal-helper-0.8.0.0 using:
      /home/michal/opt/haskell-ide-engine/.stack-work/downloaded/XcrjBfxqjaxS/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/setup --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0 configure --with-ghc=/home/michal/.stack/programs/x86_64-linux/ghc-8.0.2/bin/ghc --with-ghc-pkg=/home/michal/.stack/programs/x86_64-linux/ghc-8.0.2/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/home/michal/.stack/snapshots/x86_64-linux/lts-9.14/8.0.2/pkgdb --package-db=/home/michal/opt/haskell-ide-engine/.stack-work/install/x86_64-linux/lts-9.14/8.0.2/pkgdb --libdir=/home/michal/opt/haskell-ide-engine/.stack-work/install/x86_64-linux/lts-9.14/8.0.2/lib --bindir=/home/michal/opt/haskell-ide-engine/.stack-work/install/x86_64-linux/lts-9.14/8.0.2/bin --datadir=/home/michal/opt/haskell-ide-engine/.stack-work/install/x86_64-linux/lts-9.14/8.0.2/share --libexecdir=/home/michal/opt/haskell-ide-engine/.stack-work/install/x86_64-linux/lts-9.14/8.0.2/libexec --sysconfdir=/home/michal/opt/haskell-ide-engine/.stack-work/install/x86_64-linux/lts-9.14/8.0.2/etc --docdir=/home/michal/opt/haskell-ide-engine/.stack-work/install/x86_64-linux/lts-9.14/8.0.2/doc/cabal-helper-0.8.0.0 --htmldir=/home/michal/opt/haskell-ide-engine/.stack-work/install/x86_64-linux/lts-9.14/8.0.2/doc/cabal-helper-0.8.0.0 --haddockdir=/home/michal/opt/haskell-ide-engine/.stack-work/install/x86_64-linux/lts-9.14/8.0.2/doc/cabal-helper-0.8.0.0 --dependency=Cabal=Cabal-1.24.2.0 --dependency=base=base-4.9.1.0 --dependency=bytestring=bytestring-0.10.8.1 --dependency=directory=directory-1.3.0.0 --dependency=exceptions=exceptions-0.8.3-ADEDRATtUrMK1JW4zMQ9U --dependency=filepath=filepath-1.4.1.1 --dependency=ghc-prim=ghc-prim-0.5.0.0 --dependency=mtl=mtl-2.2.1-BLKBelFsPB3BoFeSWSOYj6 --dependency=process=process-1.4.3.0 --dependency=semigroupoids=semigroupoids-5.2.1-Db8txM8kTsI6Y49CY6g5Jn --dependency=template-haskell=template-haskell-2.11.1.0 --dependency=temporary=temporary-1.2.1.1-3IR8tQl7JQAGlaxIVThFvk --dependency=transformers=transformers-0.5.2.0 --dependency=unix=unix-2.7.2.1 --dependency=unix-compat=unix-compat-0.4.3.1-Ausmw6d7KIwA7sl52mzqxC --dependency=utf8-string=utf8-string-1.0.1.1-1DpjxLeTvGg7ttZZojxJR5 --enable-tests --enable-benchmarks
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/michal/opt/haskell-ide-engine/.stack-work/logs/cabal-helper-0.8.0.0.log

    [1 of 2] Compiling Main             ( /home/michal/opt/haskell-ide-engine/.stack-work/downloaded/XcrjBfxqjaxS/Setup.hs, /home/michal/opt/haskell-ide-engine/.stack-work/downloaded/XcrjBfxqjaxS/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/Main.o )
    [2 of 2] Compiling StackSetupShim   ( /home/michal/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /home/michal/opt/haskell-ide-engine/.stack-work/downloaded/XcrjBfxqjaxS/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/StackSetupShim.o )
    Linking /home/michal/opt/haskell-ide-engine/.stack-work/downloaded/XcrjBfxqjaxS/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/setup ...
    Warning: cabal-helper.cabal: Unknown fields: scope (line 96)
    Fields allowed in this section:
    main-is, buildable, build-tools, build-depends, cpp-options,
    cc-options, ld-options, pkgconfig-depends, frameworks,
    extra-framework-dirs, c-sources, js-sources, default-language,
    other-languages, default-extensions, other-extensions, extensions,
    extra-libraries, extra-ghci-libraries, extra-lib-dirs, includes,
    install-includes, include-dirs, hs-source-dirs, other-modules,
    ghc-prof-options, ghcjs-prof-options, ghc-shared-options,
    ghcjs-shared-options, ghc-options, ghcjs-options, jhc-options,
    hugs-options, nhc98-options
    Configuring cabal-helper-0.8.0.0...
    setup: The program 'cabal' is required but it could not be found.
```

**Comment by mgsloan** [comment] 2017-12-08 07:58
>     setup: The program 'cabal' is required but it could not be found.

It is a bad sign that cabal-helper wants to run cabal.  Generally, I find that cabal-helper and ghc-mod are messy and fragile, but that's another topic.  You might have success doing

```
stack install cabal-install
```

To install the `cabal` program.

**Comment by nponeccop** [comment] 2017-12-08 17:30
The question is how we fix that once and for all. Is there anything we can do to improve dependency management in `cabal-install` so it installs `cabal-install` the way build tools dependencies are installed?

**Comment by alanz** [comment] 2017-12-08 17:44
I'm pretty sure that one of the things cabal-helper is supposed to do is to make sure that an appropriate version of cabal is available.

Ping @DanielG

**Comment by DanielG** [comment] 2017-12-08 18:11
@mgsloan it is perfectly alright for cabal-helper do want to run `cabal`, we use it to download and install the Cabal library if needed. This isn't technically necessary for stack since we always ought to have the right version of cabal lying around somewhere but no-one ever wrote the code path to short circuit all the install logic for stack. In fact I noted this before: https://github.com/DanielG/ghc-mod/issues/725#issuecomment-171147068.

I guess we could just depend on some http library and download package tarballs directly instead of depending on `cabal-install` if anyone feels like implementing that.

**Comment by nponeccop** [comment] 2017-12-08 19:59
Is it possible to ensure that `cabal-install` is installed before `cabal-helper` by the means already available in `.cabal` and Cabal-the-library?

See https://github.com/haskell/cabal/issues/220
and https://www.haskell.org/cabal/users-guide/developing-packages.html (`build-tool-depends`)

Also I wonder if just adding `cabal-install` to dependencies, build-tools  and/or `setup-depends` will help us in any way.

**Comment by DanielG** [comment] 2017-12-08 20:18
The dependency on the `cabal` executable is declared in [Setup.hs](https://github.com/DanielG/cabal-helper/blob/master/Setup.hs#L38) but that only applies to `Cabal < 2` so I guess we should probably add cabal to `build-tool-depends` actually.

**Comment by mkunikow** [comment] 2017-12-10 10:24
`stack install cabal-install` fixed problem, thank you so much for help

**Comment by Michael2109** [comment] 2018-01-12 00:27
I've tried using `stack install cabal-install` but had no luck. Stack and Cabal are up to date. What is the solution to this?

**Comment by nponeccop** [comment] 2018-01-30 04:51
@alanz  The upstream problem is closed now. Is hie updated to use the fixed cabal-helper?

**Comment by alanz** [comment] 2018-01-30 06:58
There is now a new release of cabal-helper (0.8.0.0) but which has a bug, fixed in current master.

I am doing some final testing of the ghc-mod side of it at the moment, then will be able to push something.

**Comment by gvolpe** [comment] 2018-04-02 02:56
Hi, I'm experiencing the same issue using the latest build `57b0d7d`. Here are the details of my environment:

```
> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
> cat /proc/version
Linux version 4.13.0-37-generic (buildd@lcy01-amd64-026) (gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3.2)) #42-Ubuntu SMP Wed Mar 7 14:13:23 UTC 2018
> stack --version
Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0
> cabal --version
cabal-install version 2.0.0.1
compiled using version 2.0.1.1 of the Cabal library
``` 

I also had the `Missing C libraries: icuuc, icui18n, icudata` error but I fixed it by installing these two packages:

```
sudo apt install icu-devtools libicu-dev
```

Has anybody found a way to fix this? `stack install cabal-install` did not help.

**Comment by gvolpe** [comment] 2018-04-02 03:01
I think I'm in the wrong issue, this is the error I'm getting:

```
--  While building custom Setup.hs for package ghc-syb-utils-0.2.3.3 using:
      /home/gvolpe/.stack/setup-exe-cache/x86_64-linux-nopie/Cabal-simple_mPHDZzAJ_2.0.0.2_ghc-8.2.1 --builddir=.stack-work/dist/x86_64-linux-nopie/Cabal-2.0.0.2 build --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/gvolpe/development/haskell-ide-engine/.stack-work/logs/ghc-syb-utils-0.2.3.3.log

    Configuring ghc-syb-utils-0.2.3.3...
    Preprocessing library for ghc-syb-utils-0.2.3.3..
    Building library for ghc-syb-utils-0.2.3.3..
    [1 of 1] Compiling GHC.SYB.Utils    ( GHC/SYB/Utils.hs, .stack-work/dist/x86_64-linux-nopie/Cabal-2.0.0.2/build/GHC/SYB/Utils.o )
    /usr/bin/ld.gold: error: cannot find -ltinfo
    collect2: error: ld returned 1 exit status
    `gcc' failed in phase `Linker'. (Exit code: 1)


--  While building custom Setup.hs for package djinn-ghc-0.0.2.3 using:
      /home/gvolpe/.stack/setup-exe-cache/x86_64-linux-nopie/Cabal-simple_mPHDZzAJ_2.0.0.2_ghc-8.2.1 --builddir=.stack-work/dist/x86_64-linux-nopie/Cabal-2.0.0.2 build --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/gvolpe/development/haskell-ide-engine/.stack-work/logs/djinn-ghc-0.0.2.3.log

    Configuring djinn-ghc-0.0.2.3...
    Preprocessing library for djinn-ghc-0.0.2.3..
    Building library for djinn-ghc-0.0.2.3..
    [1 of 1] Compiling Djinn.GHC        ( src/Djinn/GHC.hs, .stack-work/dist/x86_64-linux-nopie/Cabal-2.0.0.2/build/Djinn/GHC.o )
    /usr/bin/ld.gold: error: cannot find -ltinfo
    collect2: error: ld returned 1 exit status
    `gcc' failed in phase `Linker'. (Exit code: 1)
Makefile:4: recipe for target 'build' failed
make: *** [build] Error 1
```

**Closed** 2018-06-18 07:21 UTC
Labels: component: upstream
