### ISSUE TITLE
Ghc-mod warnings and errors not shown in the list of problems in VS Code

### ISSUE THREAD

**Issue by HardRock** [haskell/haskell-ide-engine#578] opened 2018-05-18 18:50 UTC
Windows 10 Version 1709 (OS Build 16299.431)
Visual Studio Code Version 1.23.1 with Haskell Language Server 0.0.16
HIE 0.2.0.0 master branch (as of now last commit was adc51a7), built with Stack 1.7.1 and stack-8.2.2.yaml

I did my testing in a newly created stack project and edited Main.hs. To test the the errors I used this line of code:

`foo :: IO ()`

Which by itself should produce a parse error due to the accompanying binding missing, but I only get the error when I actually try to build the project.

For the warnings, I tried this simple piece of code:

`bar = 1`

Since I haven't used the name 'bar' anywhere else I would expect to get a defined but not used warning, but I do not.

It looks like ghc-mod checks are not running for me, but I'm not sure what could be the cause.

**Comment by Bubba** [comment] 2018-05-21 14:26
@HardRock if you go into the output tab and then select haskell-ide-engine does it report any errors?

**Comment by HardRock** [comment] 2018-05-21 16:49
@Bubba No errors there, this is the only output I get:

Using ghc version: Version 0.2.0.0, Git revision adc51a7c548a38823e8ce98b706dc604e41e333d (1349 commits) x86_64 ghc-8.2.2
Using hoogle db at: C:\Users\HardRock\AppData\Roaming\hoogle\default-haskell-5.0.17.hoo

**Comment by Anrock** [comment] 2018-05-21 16:59
@HardRock can you try with #588 PR?

**Comment by HardRock** [comment] 2018-05-21 18:10
@Anrock Works like a charm for the above mentioned case where I tested the error for the missing binding, now I get a ghc-mod error reported there as I type the code.

I still don't get a warning for not using the 'bar = 1' binding though, even if I add the -Wall GHC option to the newly created project.

**Comment by Anrock** [comment] 2018-05-21 19:08
@HardRock dunno about should it show by default or not, but it looks like it doesn't show warnings if there are errors present.

I've added `ghc-options: -Wall` to .cabal, restarted hie and there was a warning mark on line with `bar = 1`. As soon as i've added a `foo :: IO ()` warning mark disappeared and error mark for foo line was added. Removed the foo line - warning was back again. So i guess this thing is by design and no marks at all is a #560

**Comment by HardRock** [comment] 2018-05-21 19:52
@Anrock You are correct, on both accounts. As it turned out I made a formatting error when I added the -Wall option in stack.yaml, when placed correctly there ghc-mod will also show the warnings provided that there are no errors in a file.

All is well then at the moment. Thank you everyone for the help!

**Comment by Anrock** [comment] 2018-05-21 19:53
@HardRock given that a fix for #560 is already merged i guess you can close this issue then.

**Closed** 2018-05-21 19:53 UTC
