### ISSUE TITLE
HIE errors if NamedFieldPuns is specified in (package.yaml/project.cabal) instead of file header

### ISSUE THREAD

**Issue by CaptJakk** [haskell/haskell-ide-engine#1544] opened 2020-01-04 19:30 UTC
I don't know if this is because there is a general unawareness of "default-extensions" blocks in the project configs, or whether it is specific to NamedFieldPuns in particular. But when NamedFieldPuns is specified via a global project configuration, hie seems to be unaware of this and complains about destructuring a record like this. If it is specified in the file header, hie is happy and reports no errors.

**Comment by fendor** [comment] 2020-01-04 21:08
Thank you for this report! Does it happen with explicit cradles, too?

**Comment by fendor** [comment] 2020-01-04 23:24
Actually, can not reproduce with `cabal`
```haskell
module Foo where
data Person = Person {name :: String, address :: String}

foo Person {name} = name
```
with a cabal file:
```haskell
library
  exposed-modules:
      Foo
  hs-source-dirs:
      src
  build-depends:
      base >=4.7 && <5
      , containers, data-ordlist, unordered-containers
  default-extensions: NamedFieldPuns
  default-language: Haskell2010
```

compiles fine for me, please more details! (Assuming I am using NamedFieldPuns correctly.)

**Comment by CaptJakk** [comment] 2020-01-06 21:33
Just so we are on the same page. I have no issues with it compiling, just the editor is giving me red underlines during a NFP destructuring pattern match. Are you saying it is not giving you a red underline?

**Comment by fendor** [comment] 2020-01-06 22:06
No, it works for me in hie.

**Comment by Martinsos** [comment] 2020-01-08 22:45
I am having the same problem with `OverloadedStrings` extension, in stack project.
If I specify it in package.yaml under default-extensions, hie does not seem to pick it up and reports errors (red underline). If I put LANGUAGE pragma directly in the language, hie picks it up and there is no red underline.

Output of `hie-wrapper --debug --lsp`, run in project root:
```
2020-01-08 23:42:13.197941025 [ThreadId 4] - run entered for hie-wrapper(hie-wrapper) Version 1.0.0.0, Git revision 6fb1a548846a38a44659e5746718fbd1b1d278d9 (3570 commits) x86_64 ghc-8.6.5
2020-01-08 23:42:13.200909248 [ThreadId 4] - Current directory:/home/martin/git/wasp/stic
2020-01-08 23:42:13.201692003 [ThreadId 4] - Operating system:linux
2020-01-08 23:42:13.201989165 [ThreadId 4] - args:["--debug","--lsp"]
2020-01-08 23:42:13.203112036 [ThreadId 4] - Cabal-Helper found these projects: ["ProjLocStackYaml {plStackYaml = \"/home/martin/git/wasp/stic/stack.yaml\"}","ProjLocV2Dir {plProjectDirV2 = \"/home/martin/git/wasp/stic\"}","ProjLocV1Dir {plProjectDirV1 = \"/home/martin/git/wasp/stic\"}"]
2020-01-08 23:42:13.204111169 [ThreadId 4] - These projects have the build tools installed: ["ProjLocStackYaml {plStackYaml = \"/home/martin/git/wasp/stic/stack.yaml\"}","ProjLocV2Dir {plProjectDirV2 = \"/home/martin/git/wasp/stic\"}","ProjLocV1Dir {plProjectDirV1 = \"/home/martin/git/wasp/stic\"}"]
2020-01-08 23:42:13.207058046 [ThreadId 4] - Cabal-Helper decided to use: ProjLocStackYaml {plStackYaml = "/home/martin/git/wasp/stic/stack.yaml"}
2020-01-08 23:42:13.207501932 [ThreadId 4] - Cabal-Helper dirs: ["/home/martin/git/wasp/stic","/home/martin/git/wasp/stic/File.hs"]
2020-01-08 23:42:14.910939625 [ThreadId 4] - Cabal-Helper cradle package: Package {pPackageName = "stic", pSourceDir = "/home/martin/git/wasp/stic", pCabalFile = CabalFile "/home/martin/git/wasp/stic/stic.cabal", pFlags = [], pUnits = Unit {uUnitId = UnitId "stic", uPackage = Package {pPackageName = "stic", pSourceDir = "/home/martin/git/wasp/stic", pCabalFile = CabalFile "/home/martin/git/wasp/stic/stic.cabal", pFlags = [], pUnits = ()}, uDistDir = DistDirLib "/home/martin/git/wasp/stic/.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1", uImpl = UnitImplStack} :| []}
2020-01-08 23:42:14.912942743 [ThreadId 4] - Cabal-Helper normalisedPackageLocation: /home/martin/git/wasp/stic
2020-01-08 23:42:14.913325337 [ThreadId 4] - Module "/home/martin/git/wasp/stic/File.hs" is loaded by Cradle: Cradle {cradleRootDir = "/home/martin/git/wasp/stic", cradleOptsProg = CradleAction: Cabal-Helper-Stack}
2020-01-08 23:42:14.913942707 [ThreadId 4] - Cradle directory:/home/martin/git/wasp/stic
2020-01-08 23:42:14.914279631 [ThreadId 4] - Use Stack GHC
2020-01-08 23:42:15.305405804 [ThreadId 4] - GHC Output: "Just "8.6.3""
2020-01-08 23:42:15.30581885 [ThreadId 4] - Project GHC version:8.6.3
2020-01-08 23:42:15.3061311 [ThreadId 4] - hie exe candidates :["hie-8.6.3","hie-8.6","hie"]
2020-01-08 23:42:15.306791696 [ThreadId 4] - found hie exe at:/usr/bin/hie-8.6.3
2020-01-08 23:42:15.307142094 [ThreadId 4] - args:["--debug","--lsp"]
2020-01-08 23:42:15.307450967 [ThreadId 4] - launching ....



2020-01-08 23:42:15.310134538 [ThreadId 4] - Run entered for HIE(hie-8.6.3) Version 1.0.0.0, Git revision 6fb1a548846a38a44659e5746718fbd1b1d278d9 (3570 commits) x86_64 ghc-8.6.3
2020-01-08 23:42:15.310410526 [ThreadId 4] - Operating as a LSP server on stdio
2020-01-08 23:42:15.310472599 [ThreadId 4] - Current directory:/home/martin/git/wasp/stic
2020-01-08 23:42:15.310523844 [ThreadId 4] - Operating system:linux
2020-01-08 23:42:15.310579378 [ThreadId 4] - args:["--debug","--lsp"]
2020-01-08 23:42:15.310723164 [ThreadId 4] - 




haskell-lsp:Starting up server ...

```

**Comment by fendor** [comment] 2020-01-08 22:54
@Martinsos I think your logs are incomplete. There should be much, much more!

**Comment by Martinsos** [comment] 2020-01-08 23:05
Hmmm, you are probably expecting logs caused by communication of editor with the lsp server? The thing is, I am using emacs, and what I posted is just what I get when I run hei directly in the console. I am not sure how can I get debug output of hei that emacs is running?

Btw. I tried defining cradle, but it does not seem to affect anything.
I created hei.yaml in project root:
```yaml
cradle:
  stack:
    - path: "./src/"
      component: "stic:lib"
    - path: "./app/"
      component: "stic:exe:stic-exe"
    - path: "./test"
      component: "stic:test:stic-test"
``` 

where my package.yaml is
```yaml
# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
... stuff ...

default-extensions:
  - OverloadedStrings

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall

library:
  source-dirs: src
  dependencies:
    - filepath
    - parsec
    - mustache
    - text
    - aeson
    - directory
    - split

executables:
  stic-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - stic
      - filepath

benchmarks:
  stic-benchmarks:
    main:                Main.hs
    source-dirs:         benchmark
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - stic
      - criterion

tests:
  stic-test:
    main:                TastyDiscoverDriver.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aeson
      - filepath
      - text
      - mtl
      - stic
      - tasty
      - tasty-hspec
      - tasty-quickcheck
      - tasty-discover
      - QuickCheck
      - parsec

```

**Comment by alanz** [comment] 2020-01-08 23:09
```yaml
default-extensions:
  - OverloadedStrings
```

This does not have `NamedFieldPuns`?

**Comment by Martinsos** [comment] 2020-01-08 23:10
> ```yaml
> default-extensions:
>   - OverloadedStrings
> ```
> 
> This does not have `NamedFieldPuns`?

No, I am having problem with another extension, OverloadedStrings. I don't think the whole issue is related to specific extension, it seems to instead be caused by default extensions.

**Comment by alanz** [comment] 2020-01-08 23:11
Ok, just checking, thanks.

**Comment by fendor** [comment] 2020-01-08 23:15
@Martinsos Assuming you named the file `hie.yaml` that looks correct. 
Unfortunately, I dont know how to obtain the logs with emacs, either.
Can you maybe share a project? Or does it not work on a basic stack project, too? No diagnostics or anything?

**Comment by Martinsos** [comment] 2020-01-08 23:17
@fendor I can't share project unfortunately, and I also did not try it on basic stack project yet.
I understand that you will need more information from my side to figure this out -> I will try to do smth to get it, either figure out how to get information in emacs or try on basic stack project or smth! I will get back to you then, probably tomorrow. Thanks for help so far!

**Comment by Martinsos** [comment] 2020-01-09 00:25
@fendor I managed to get some logs:

```
Flags for "/home/martin/git/wasp/stic/src/Wasp/Entity.hs": ["-fbuilding-cabal-package","-O","-outputdir",".stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build","-odir",".stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build","-hidir",".stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build","-stubdir",".stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build","-i","-i/home/martin/git/wasp/stic/.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build","-i/home/martin/git/wasp/stic/src","-i/home/martin/git/wasp/stic/.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/autogen","-i/home/martin/git/wasp/stic/.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/global-autogen","-I.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/autogen","-I.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/global-autogen","-I.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build","-optP-include","-optP.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/autogen/cabal_macros.h","-this-unit-id","stic-0.1.0.0-9ZYewXWoS2gARP3hFVil5e","-hide-all-packages","-Wmissing-home-modules","-no-user-package-db","-package-db","/home/martin/.stack/snapshots/x86_64-linux-tinfo6/3be2734f7e71638815c88fd2fe85fcfe693d29dd5b733972790a6b5c0b5988c4/8.6.3/pkgdb","-package-db","/home/martin/git/wasp/stic/.stack-work/install/x86_64-linux-tinfo6/3be2734f7e71638815c88fd2fe85fcfe693d29dd5b733972790a6b5c0b5988c4/8.6.3/pkgdb","-package-id","aeson-1.4.2.0-JRlZKD1FkrO2eJjy3cMEtP","-package-id","base-4.12.0.0","-package-id","directory-1.3.3.0","-package-id","filepath-1.4.2.1","-package-id","mustache-2.3.0-Ang5DrQXNKrCe1RvUBWCoj","-package-id","parsec-3.1.13.0","-package-id","split-0.2.3.3-6n1iQ0JLFvkeXvJXsAqQc","-package-id","text-1.2.3.1","-XHaskell2010","-XOverloadedStrings","-Wall", ... HERE NOW GOES LIST OF HASKELL MODULES
```
Important to notice here is that it does pass OverloadedStrings as an extension flag.

Then there is this block:
```
Component Infos: ChComponentInfo {ciComponentName = ChLibName ChMainLibName, ciGhcOptions = ["-fbuilding-cabal-package","-O","-outputdir",".stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build","-odir",".stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build","-hidir",".stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build","-stubdir",".stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build","-i","-i.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build","-isrc","-i.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/autogen","-i.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/global-autogen","-I.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/autogen","-I.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/global-autogen","-I.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build","-optP-include","-optP.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/autogen/cabal_macros.h","-this-unit-id","stic-0.1.0.0-9ZYewXWoS2gARP3hFVil5e","-hide-all-packages","-Wmissing-home-modules","-no-user-package-db","-package-db","/home/martin/.stack/snapshots/x86_64-linux-tinfo6/3be2734f7e71638815c88fd2fe85fcfe693d29dd5b733972790a6b5c0b5988c4/8.6.3/pkgdb","-package-db","/home/martin/git/wasp/stic/.stack-work/install/x86_64-linux-tinfo6/3be2734f7e71638815c88fd2fe85fcfe693d29dd5b733972790a6b5c0b5988c4/8.6.3/pkgdb","-package-id","aeson-1.4.2.0-JRlZKD1FkrO2eJjy3cMEtP","-package-id","base-4.12.0.0","-package-id","directory-1.3.3.0","-package-id","filepath-1.4.2.1","-package-id","mustache-2.3.0-Ang5DrQXNKrCe1RvUBWCoj","-package-id","parsec-3.1.13.0","-package-id","split-0.2.3.3-6n1iQ0JLFvkeXvJXsAqQc","-package-id","text-1.2.3.1","-XHaskell2010","-XOverloadedStrings","-Wall"], ciSourceDirs = ["src"], ciEntrypoints = ChLibEntrypoint {chExposedModules = [ChModuleName {unChModuleName = "Wasp"},ChModuleName {unChModuleName = "Wasp.App"},ChModuleName {unChModuleName = "Wasp.App_flymake"},ChModuleName {unChModuleName = "Wasp.Entity"},ChModuleName {unChModuleName = "Wasp.Entity_flymake"},ChModuleName {unChModuleName = "Wasp.EntityForm"}], chOtherModules = [ChModuleName {unChModuleName = "Paths_stic"}], chSignatures = []}}
```

I don't really understand what this is, but I do notice that it has _flymake versions of components only for those which I opened in editor (emacs). Btw there is more components but I "censored" the rest.

Finally, then comes the error (but I have no idea if this is some critical error or just survivable error):
```
Source error on cradle initialisation: File name does not match module name:
Saw: ‘Wasp.App’
Expected: ‘Wasp.App_flymake’

2020-01-09 01:10:25.905935459 [ThreadId 236] - Modules in the cradle: []
2020-01-09 01:10:25.90597789 [ThreadId 236] - Cradle did not load succesfully
```

There are of course more logs, but I would need to do some cleaning up of those before sharing so I am posting for now only what I hope is most relevant.

I did some more digging and testing in general and I actually think that wrong higlights that I am getting are maybe not coming from hie at all, but from haskell-mode in emacs -> because if I turn off lsp in emacs, I get the same errors from haskell-mode. I am guessing that is happening because lsp in emacs fails to work properly and falls back to haskell-mode, but that is wild speculation.

@CaptJakk are you by any chance also having this problem in emacs, what is your editor?

**Comment by Martinsos** [comment] 2020-01-09 01:06
I am really not sure anymore if problem is coming from hie, from lsp, lsp-haskell or my emacs configuration. If you have any ideas here, great, if not I will assume it is on the emacs side and will try to figure that out. Thanks!

**Comment by fendor** [comment] 2020-01-09 12:01
> Finally, then comes the error (but I have no idea if this is some critical error or just survivable error):

I think this is a survivable error. It definitely is if hover requests in other files still show something. When we dont survive something, any ghc related functionality crashes. While I am not sure what `_flymake` is (it is some extension, iirc?), the other modules should load normally. 

It is possible that this error is not caused by hie if you have other extensions, too. As said, it *should* work, we are using it in hie on a daily basis and I use it in private projects, too.

**Comment by Martinsos** [comment] 2020-01-09 13:00
> > Finally, then comes the error (but I have no idea if this is some critical error or just survivable error):
> 
> I think this is a survivable error. It definitely is if hover requests in other files still show something. When we dont survive something, any ghc related functionality crashes. While I am not sure what `_flymake` is (it is some extension, iirc?), the other modules should load normally.
> 
> It is possible that this error is not caused by hie if you have other extensions, too. As said, it _should_ work, we are using it in hie on a daily basis and I use it in private projects, too. However, since there can be many different project set-ups, a bug might have snuck in somewhere.

I think you are right, and sorry for false alarm from my side! I will investigate further on the emacs side, now I know to focus there. Thanks again for help!

**Comment by fendor** [comment] 2020-01-26 17:18
Closing for now, feel free to open again if problems persist.

**Closed by fendor** 2020-01-26 17:18 UTC
