### ISSUE TITLE
HIE reports invalid file uri on Windows

### ISSUE THREAD

**Issue by Anrock** [haskell/haskell-ide-engine#329] opened 2017-10-11 21:23 UTC
See https://github.com/autozimu/LanguageClient-neovim/issues/144
Looks like diagnostics from ghcmod are using invalid file path separator.

**Comment by Anrock** [comment] 2017-10-12 22:37
@alanz please take a look.

**Comment by alanz** [comment] 2017-10-13 08:16
Can you try again with current HIE master?

**Comment by Anrock** [comment] 2017-10-13 11:37
@alanz Master stopped building on Win since 8b9b623 because of `unix` dep in `hie-build-plugin-0.1.0.0`
Latest buildable commit: 7f77e7e, issue still present there.

**Comment by alanz** [comment] 2017-10-13 12:34
Where is the `unix` dep? Any idea what is bringing it in?

**Comment by Anrock** [comment] 2017-10-13 13:22
I have no idea right now. 
It looks like haskell tooling doesn't have something to list full dependency tree of package (omg, why?), so the only viable option i see now is to analyze diff of broken commit and find introduced dependency manually.

**Comment by Anrock** [comment] 2017-10-13 13:36
@alanz found it.
In 8b9b623 you switched from alanz/cabal-helper `94b7ad` to DanielG/cabal-helper `4af5dddb`
Previous commit of DanielG/cabal-helper `4af5dddb` - `4b3571a` introduces `unix` package to use instead of `time`.

**Comment by Anrock** [comment] 2017-10-13 14:35
@alanz so i've used local repo of cabal-helper with `4b357a` reverted, hie built fine.
Still file uri is wrong:
```
17:26:23 DEBUG   [RPC-haskell] <= {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///C:\\Users\\Anrock\\Desktop\\test.hs","diagnostics":[{"severity":1,"range":{"start":{"line":5,"character":8},"end":{"line":5,"character":12}},"source":"ghcmod","message":"Parse error: naked expression at top level\nPerhaps you intended to use TemplateHaskell"}]}}
```

**Comment by alanz** [comment] 2017-10-13 14:47
Ok, thanks.

Can you paste an edited version of what you would be expecting to see?

**Comment by Anrock** [comment] 2017-10-13 14:54
> Can you paste an edited version of what you would be expecting to see?
You mean edited server response? Honestly i have no idea how LSP protocol works.

As far as i understood explanations of @autozimu in autozimu/LanguageClient-neovim#144 and [reference](https://en.wikipedia.org/wiki/File_URI_scheme#Windows) [urls](https://blogs.msdn.microsoft.com/ie/2006/12/06/file-uris-in-windows/) he posted 
offending path is in `params.uri`
```
file:///C:\\Users\\Anrock\\Desktop\\test.hs
```
and it should look like
```
file:///c:/Users/Anrock/Desktop/test.hs
```
just like hlint reports it.

**Comment by michael8090** [comment] 2017-11-10 17:11
any update here?

**Comment by alanz** [comment] 2017-11-10 18:04
I lost track of this, tbh. Sorry.

I will see what I can do this weekend.

**Comment by Anrock** [comment] 2017-11-10 21:09
@alanz so i've managed to build HIE using master DanielG/cabal-helper on Windows (just changed git link and added `semigroupoids-5.2.1` to `extra-deps` in `stack.yaml`, can make a PR).

Since latest Windows-buildable commit HIE paths had improved!
Was: `file:///C:\\Users\\Anrock\\Desktop\\test.hs`
Now: `file:///c%3A/Users/Anrock/test.hs`
Sadly, diagnostics in neovim still don't work :(
I guess that's because of `c%3A` instead of `C:`.

Is there somehow i can help? Like if you point me to place where paths are processed maybe i can hack it myself a little bit and make a ugly-but-working PR?

**Comment by Anrock** [comment] 2017-11-10 22:20
And my little investigation goes on. I've managed to find a place where windows paths are processed:
`src/Language/Haskell/LSP/TH/DataTypesJSON.hs` in https://gitlab.com/alanz/haskell-lsp.
Looks like [this commit](https://gitlab.com/alanz/haskell-lsp/commit/6b9923f56c86cbd63e9b887d6603602605be7e2a) added `%3a` piece, so i replaced it back with `:` and removed `toLower` of drive letter. Hlint errors were fixed by that.
Ghc-mod ones still don't work:
```
01:14:39 INFO    [MainThread] textDocument/didChange
01:14:39 DEBUG   [MainThread] => {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"file:///C:/Users/Anrock/test.hs","version":8},"contentChanges":[{"text":"data D = A | B\n\nf :: Sring -> String\nf = undefined\n"}]}}
01:14:39 DEBUG   [RPC-haskell] <= {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///C:/Users/Anrock/test.hs","diagnostics":[]}}
01:14:39 DEBUG   [MainThread] state.file:///C:/Users/Anrock/test.hs.diagnostics: [] => []
01:14:39 DEBUG   [MainThread] state.file:///C:/Users/Anrock/test.hs.line_diagnostics: {} => {}
01:14:39 DEBUG   [MainThread] state.file:///C:/Users/Anrock/test.hs.signs: [] => []
01:14:39 DEBUG   [RPC-haskell] <= {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///C:/Users/Anrock/AppData/Local/Temp/ghc-mod10861/test633426500.hs","diagnostics":[{"severity":1,"range":{"start":{"line":2,"character":5},"end":{"line":2,"character":10}},"source":"ghcmod","message":"Not in scope: type constructor or class `Sring'\nPerhaps you meant `String' (imported from Prelude)"}]}}
01:14:39 DEBUG   [RPC-haskell] <= {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///C:/Users/Anrock/test.hs","diagnostics":[]}}
01:14:39 DEBUG   [MainThread] state.file:///C:/Users/Anrock/AppData/Local/Temp/ghc-mod10861/test633426500.hs.diagnostics: [{'severity': 1, 'range': {'start': {'line': 2, 'character': 5}, 'end': {'line': 2, 'character': 10}}, 'source': 'ghcmod', 'message': "Not in scope: type constructor or class `Sring'\nPerhaps you meant `String' (imported from Prelude)"}] => [{'severity': 1, 'range': {'start': {'line': 2, 'character': 5}, 'end': {'line': 2, 'character': 10}}, 'source': 'ghcmod', 'message': "Not in scope: type constructor or class `Sring'\nPerhaps you meant `String' (imported from Prelude)"}]
01:14:39 DEBUG   [MainThread] state.file:///C:/Users/Anrock/AppData/Local/Temp/ghc-mod10861/test633426500.hs.line_diagnostics: {2: "[Error] Not in scope: type constructor or class `Sring'\nPerhaps you meant `String' (imported from Prelude)"} => {2: "[Error] Not in scope: type constructor or class `Sring'\nPerhaps you meant `String' (imported from Prelude)"}
01:14:39 DEBUG   [MainThread] state.file:///C:/Users/Anrock/test.hs.diagnostics: [] => []
01:14:39 DEBUG   [MainThread] state.file:///C:/Users/Anrock/test.hs.line_diagnostics: {} => {}
01:14:39 DEBUG   [MainThread] state.file:///C:/Users/Anrock/test.hs.signs: [] => []
```
Looks like HIE reports temporary file path instead of one being edited in nvim. Now i'm looking for a place wher file path is produced...

**Comment by Anrock** [comment] 2017-11-12 00:30
Little update. 
I've traced temp path source to `hie-ghc-mod/Haskell/Ide/GhcModPlugin.hs#setTypeCheckedModule`. It cames from `GM.getTypecheckedModuleGhc' (myLogger rfm) fp` call, which returns a bunch of diagnostic messages for `fp` (file path, i guess). While `fp`  is correct, diagnostics are returned with uri pointing to temporary file. 
Now i'm going to investigate ghc-mod (oh god) to determine if `getTypecheckedModuleGhc'` does the right thing or not and what `GM.mkRevRedirMapFunc` does at all. From the name of it and it's enclosing function, `mkdRevRedirMapFunc`  probably somehow related to `revMap` - mapping between ghc-mod temp files and actual files. And probably it doesn't work.

**Comment by Anrock** [comment] 2017-11-15 11:33
@alanz i'm kinda stuck. 
I think `rfm` doesn't return mapped file and returns argument as is. And i can't find a way to check this - can't write to hie log from ghc-mod and can't find how to access `getMMappedFiles` in hie code. Any advice?

**Comment by alanz** [comment] 2017-11-16 11:16
I am impressed at your progress with this.  I will be updating hie shortly to use the newer cabal-helper, and will take a look at this.

But it is hard for me, not being on windows.

**Comment by Anrock** [comment] 2017-11-16 11:23
@alanz we can catch up on irc and do a live debugging session, for example

**Comment by michael8090** [comment] 2017-11-20 14:03
Thanks for your quick response, now it can build on windows! 

I've spent the whole weekend on trying to setting up a decent hasekll developing environment on windows for learning the language but with no luck. This is the only thing I feel comfortable to work with. Great job!

**Comment by alanz** [comment] 2017-11-20 14:33
But it is still giving the incorrect path in error messages?

**Comment by Anrock** [comment] 2017-11-20 16:59
@alanz yup, still reporting diagnostics for temporary ghc-mod file instead of actually edited.

**Comment by alanz** [comment] 2017-11-20 17:30
As expected

**Comment by nponeccop** [comment] 2017-12-04 06:52
I couldn't reproduce the bug with temporary files. I receive normal:

**Comment by Anrock** [comment] 2017-12-04 07:33
@nponeccop yay! Which cabal-helper (project, commit) are you using?

**Comment by nponeccop** [comment] 2017-12-04 07:53
See the PR. Also check whether you have build failures in `%temp%\LanguageServer.log`

**Comment by nponeccop** [comment] 2017-12-11 01:50
Current status of this bug is that we wait for various fixes if @wz1000 to be merged, and then we'll see what to do with https://github.com/alanz/haskell-lsp/pull/63 which fixes this incorrect `%3a` escaping

**Comment by Anrock** [comment] 2017-12-20 18:55
@nponeccop could you please list PRs with 'various of @wz1000' so i can track progress on this?

**Comment by nponeccop** [comment] 2017-12-21 01:58
The 'various fixes' (18 commits) have been already merged in https://github.com/haskell/haskell-ide-engine/pull/403

However the https://github.com/alanz/haskell-lsp/pull/63 is still not merged and neither @alanz nor @wz1000 have replied there.

As a workaround for now you can change `stack.yaml` to use `haskell-lsp` from that branch instead of from hackage.

**Comment by Anrock** [comment] 2018-03-25 11:25
@alanz @nponeccop haven't seen this issue in a while. I guess it can be closed.

**Comment by nponeccop** [comment] 2018-03-25 16:40
I vote for closing

**Closed** 2018-03-25 17:09 UTC
Labels: os: windows, status: need confirmation
