### ISSUE TITLE
Occurred error on stack new-template.

### ISSUE THREAD

**Issue by dyoshikawa** [haskell/haskell-ide-engine#1706] opened 2020-03-16 04:34 UTC
# Environment

- MacOS Mojave 10.14.6
- VSCode 1.43.0
- stack 1.2
- hie 1.2, Git revision 35f62cffb6bae6c3f86113cb0c55f52b7192689d (3841 commits) x86_64 ghc-8.6.5

# Reproduction steps

```
stack new my-project --resolver ghc-8.6.5
```

Generated sources of [new-template](https://github.com/commercialhaskell/stack-templates/blob/master/new-template.hsfiles).

```
cd my-project
code . # open vscode
```

When open `Setup.hs` on vscode, the error occurred.

# Error Message

```
Fail on initialisation for "/Users/username/src/github.com/username/my-project/Setup.hs".
Could not obtain flags for: "Setup.hs".

This module was not part of any component we are aware of.

Component: ChLibName ChMainLibName with source directory: ["src"]
Component: ChExeName "my-project-exe" with source directory: ["app"]
Component: ChTestName "my-project-test" with source directory: ["test"]


To expose a module, refer to:
https://docs.haskellstack.org/en/stable/GUIDE/
If you are using `package.yaml` then you don't have to manually expose modules.
Maybe you didn't set the source directories for your project correctly.
```

`stack build` is completed successfully.
Do you have any idea?

**Comment by jneira** [comment] 2020-03-16 07:29
`Setup.hs` is a special file and hie does not have support for it yet. You should be abale to open other files (inside src or exe dirs) though.
See https://github.com/haskell/haskell-ide-engine/issues/1650

**Comment by dyoshikawa** [comment] 2020-03-16 08:36
@jneira Thank you.
I will watch #1650 discussion.

**Comment by fendor** [comment] 2020-03-16 08:37
Feel free to reopen, if it turns out, it wasnt a duplicate of #1650

**Closed** 2020-03-16 08:37 UTC
