### ISSUE TITLE
LanguageClient error - "haskell-lsp: no handler for" (NeoVim)

### ISSUE THREAD

**Issue by andregpss** [haskell/haskell-ide-engine#1614] opened 2020-01-29 02:57 UTC
I'm using HIE on NeoVim v0.4.3, on Ubuntu Linux (over WSK Windows 10), but `LanguageClient ` plug-in is not working. 

However, `Coc` plugin is working perfectly (code completion showing documentation). `HLint `is also working.

The error below is shown everytime i open a `.hs` file:
```
[LC] [Error] haskell-lsp:no handler for. Object (fromList [("jsonrpc",String "2.0"),("params",Object (fromList [("textDocument",Object (fromList [("uri",String "file:///mnt/c/Users/Me/Project/ServerMain.hs")]))])),("method",String "textDocument/codeLens"),("id",Number 2.0)])
"## Output channel: languegeserver.haskell"
```

When i press `F5`, `LanguageClient` menu appears, but all comands shows the same message: 
> [LC] Not found!

I updated HIE project on 27-jan-2020. I compiled it for GHC-8.6.5. This is the GHC version i use.

On `init.vim`, the `LanguageClient `configuration is:
```vim
set rtp+=~/.vim/pack/XXX/start/LanguageClient-neovim
let g:LanguageClient_serverCommands = { 'haskell': ['hie-wrapper', '--lsp'] }
let g:LanguageClient_rootMarkers = ['*.cabal', 'stack.yaml']
nnoremap <F5> :call LanguageClient_contextMenu()<CR>
map <Leader>lk :call LanguageClient#textDocument_hover()<CR>
map <Leader>lg :call LanguageClient#textDocument_definition()<CR>
map <Leader>lr :call LanguageClient#textDocument_rename()<CR>
map <Leader>lf :call LanguageClient#textDocument_formatting()<CR>
map <Leader>lb :call LanguageClient#textDocument_references()<CR>
map <Leader>la :call LanguageClient#textDocument_codeAction()<CR>
map <Leader>ls :call LanguageClient#textDocument_documentSymbol()<CR>
call plug#begin()
Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install()}}
Plug 'neovimhaskell/haskell-vim'
Plug 'preservim/nerdtree' 
Plug 'liuchengxu/vista.vim' 
Plug 'itchyny/lightline.vim'
Plug 'nbouscal/vim-stylish-haskell'
Plug 'autozimu/LanguageClient-neovim', { 
    \ 'branch': 'next',
    \ 'do': './install.sh'
    \ }	
call plug#end()
```

**Comment by Avi-D-coder** [comment] 2020-01-29 03:45
You should use Coc or LanguageClient-neovim, not both. I advise Coc.

**Comment by andregpss** [comment] 2020-01-29 03:55
> You should use Coc or LanguageClient-neovim, not both. I advise Coc.

@Avi-D-coder But  how can i know the type definition of a variable using only Coc? I think LAnguageClient has more features than Coc, isnt it? Why did you advise Coc? Thanks.

**Comment by Avi-D-coder** [comment] 2020-01-29 04:02
Coc is a complete LSP implementation based on vscodes's implementation, it supports more features than LCN.

See the example [Coc config](https://github.com/neoclide/coc.nvim#example-vim-configuration) and it's [wiki](https://github.com/neoclide/coc.nvim/wiki/Language-servers).

**Comment by Avi-D-coder** [comment] 2020-01-29 19:36
I'm going to close this, since the issue is due to using two clients at once. If you have any questions or the issue occurs when using a single client just add a comment.

**Closed by Avi-D-coder** 2020-01-29 19:36 UTC

**Comment by andregpss** [comment] 2020-01-30 01:06
Ok.
I uninstalled LanguageClient from NeoVim.
I did not know that Coc is so powerful, and that we can set so much parameters to the coc config.
I think it is a good idea to put the link to [Coc config](https://github.com/neoclide/coc.nvim#example-vim-configuration) on the [HIE installation settings.](https://github.com/haskell/haskell-ide-engine#coc)
