### ISSUE TITLE
No ghc installations found in $PATH.

### ISSUE THREAD

**Issue by fuszenecker** [haskell/haskell-ide-engine#1760] opened 2020-05-04 08:54 UTC
Hi,

When building HIE with cabal, I received the following error message:

```
[1 of 1] Compiling Main             ( Main.hs, C:\work\dev\haskell-ide-engine\dist-newstyle\build\x86_64-windows\ghc-8.10.1\fake-package-0\x\script\build\script\script-tmp\Main.o )
Linking C:\work\dev\haskell-ide-engine\dist-newstyle\build\x86_64-windows\ghc-8.10.1\fake-package-0\x\script\build\script\script.exe ...

********************************************************************************
No ghc installations found in $PATH.
The script requires at least one ghc in $PATH to be able to build hie.

********************************************************************************

No ghc installations found in $PATH.
The script requires at least one ghc in $PATH to be able to build hie.

CallStack (from HasCallStack):
  error, called at src\Env.hs:75:3 in hie-install-0.8.1.0-inplace:Env
```

The command I used to build HIE is:

```
 .\cabal-hie-install.cmd hie
```

Environment:
* Windows 10 64-bit,
* ghc 8.10.1 (installed with `choco`),
* cabal 3.2.0.0,
* HIE master `commit d9d21fb0675280e20e837dbeb5715dab65e9c6be (HEAD -> master, tag: 1.4, origin/master, origin/HEAD)`.

**Comment by fendor** [comment] 2020-05-04 09:02
Thank you for your bug report!
This seems to be a duplicate of https://github.com/haskell/haskell-ide-engine/issues/1646

Essentially, you have `ghc-8.10.1` but HIE doesnt support `ghc-8.10.1`. The message is just wrong and it is generated because we filter all available ghc by supported ghc versions.

**Closed** 2020-05-04 09:50 UTC
Labels: resolution: duplicate, type: bug

**Comment by fuszenecker** [comment] 2020-05-04 10:07
Thank you very much
* for the information,
* and for Haskell IDE Engine that is an outstanding tool for Haskell development.
